# uRTMv2 xc7k325tffg900-2
# Version 2022-05-28
set_property  SEVERITY {Warning} [get_drc_checks UCIO-1]
set_property  SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property  BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

######################################################################
# Reset
set_property  PACKAGE_PIN R23           [get_ports "RST_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RST_B"]

######################################################################
# Clock
create_clock  -period 5.00 -name REFCLK [get_ports "CLK_IN_200_P"]
set_property  PACKAGE_PIN D17           [get_ports "CLK_IN_200_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_IN_200_P"]
set_property  PACKAGE_PIN D18       	[get_ports "CLK_IN_200_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_IN_200_N"]

create_clock  -period 25.0 -name PLLCLK [get_ports "CLK_IN_PL_P"]
set_property  PACKAGE_PIN AG29          [get_ports "CLK_IN_PL_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_IN_PL_P"]
set_property  PACKAGE_PIN AH29          [get_ports "CLK_IN_PL_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_IN_PL_N"]

create_clock  -period 8.0 -name SWCLK   [get_ports "CLK_IN_SW_P"]
set_property  PACKAGE_PIN AG10          [get_ports "CLK_IN_SW_P"]
set_property  IOSTANDARD  DIFF_SSTL135  [get_ports "CLK_IN_SW_P"]
set_property  PACKAGE_PIN AH10          [get_ports "CLK_IN_SW_N"]
set_property  IOSTANDARD  DIFF_SSTL135  [get_ports "CLK_IN_SW_N"]

set_property  PACKAGE_PIN Y23           [get_ports "CLK_OUT_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_P"]
set_property  PACKAGE_PIN Y24           [get_ports "CLK_OUT_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "CLK_OUT_N"]

######################################################################
# I/O
set_property  PACKAGE_PIN AB12          [get_ports "DIPSW[0]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DIPSW[0]"]
set_property  PULLUP      true          [get_ports "DIPSW[0]"]
set_property  PACKAGE_PIN AA12          [get_ports "DIPSW[1]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DIPSW[1]"]
set_property  PULLUP      true          [get_ports "DIPSW[1]"]
set_property  PACKAGE_PIN Y11           [get_ports "DIPSW[2]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DIPSW[2]"]
set_property  PULLUP      true          [get_ports "DIPSW[2]"]
set_property  PACKAGE_PIN Y10           [get_ports "DIPSW[3]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DIPSW[3]"]
set_property  PULLUP      true          [get_ports "DIPSW[3]"]
set_property  PACKAGE_PIN AC9           [get_ports "DIPSW[4]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DIPSW[4]"]
set_property  PULLUP      true          [get_ports "DIPSW[4]"]
set_property  PACKAGE_PIN AB9           [get_ports "DIPSW[5]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DIPSW[5]"]
set_property  PULLUP      true          [get_ports "DIPSW[5]"]
set_property  PACKAGE_PIN AB8           [get_ports "DIPSW[6]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DIPSW[6]"]
set_property  PULLUP      true          [get_ports "DIPSW[6]"]
set_property  PACKAGE_PIN AA8           [get_ports "DIPSW[7]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DIPSW[7]"]
set_property  PULLUP      true          [get_ports "DIPSW[7]"]

set_property  PACKAGE_PIN T27           [get_ports "TESTPIN[0]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "TESTPIN[0]"]
set_property  PACKAGE_PIN T26           [get_ports "TESTPIN[1]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "TESTPIN[1]"]
set_property  PACKAGE_PIN T28           [get_ports "TESTPIN[2]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "TESTPIN[2]"]
set_property  PACKAGE_PIN R28           [get_ports "TESTPIN[3]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "TESTPIN[3]"]

# RED
set_property  PACKAGE_PIN V29           [get_ports "RGBLED[0]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RGBLED[0]"]
# GREEN
set_property  PACKAGE_PIN P28           [get_ports "RGBLED[1]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RGBLED[1]"]
# BLUE
set_property  PACKAGE_PIN V30           [get_ports "RGBLED[2]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RGBLED[2]"]

# LEMO interface
set_property  PACKAGE_PIN K28           [get_ports "LEMO_IN_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "LEMO_IN_P"]
set_property  PACKAGE_PIN K29           [get_ports "LEMO_IN_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "LEMO_IN_N"]

# IIC
set_property  PACKAGE_PIN R30           [get_ports "FPGA_SCL"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FPGA_SCL"]
set_property  PACKAGE_PIN T30           [get_ports "FPGA_SDA"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FPGA_SDA"]

# UART
set_property  PACKAGE_PIN U24           [get_ports "UART_TX"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "UART_TX"]
set_property  PACKAGE_PIN V24           [get_ports "UART_RX"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "UART_RX"]

# FAN
set_property  PACKAGE_PIN V27           [get_ports "FANFAIL_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FANFAIL_B"]
set_property  PACKAGE_PIN V26           [get_ports "OT_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "OT_B"]

# FLASH Interface
# set_property  PACKAGE_PIN P24           [get_ports "FLASH_D[0]"]
# set_property  IOSTANDARD  LVCMOS33      [get_ports "FLASH_D[0]"]
# set_property  PACKAGE_PIN R25           [get_ports "FLASH_D[1]"]
# set_property  IOSTANDARD  LVCMOS33      [get_ports "FLASH_D[1]"]
# set_property  PACKAGE_PIN R20           [get_ports "FLASH_D[2]"]
# set_property  IOSTANDARD  LVCMOS33      [get_ports "FLASH_D[2]"]
# set_property  PACKAGE_PIN R21           [get_ports "FLASH_D[3]"]
# set_property  IOSTANDARD  LVCMOS33      [get_ports "FLASH_D[3]"]
# set_property  PACKAGE_PIN U19           [get_ports "FLASH_CS_B"]
# set_property  IOSTANDARD  LVCMOS33      [get_ports "FLASH_CS_B"]

######################################################################
# FMC2
set_property  PACKAGE_PIN P29           [get_ports "FMC2_PRSNT_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC2_PRSNT_B"]

set_property  PACKAGE_PIN AD23          [get_ports "FMC2_CLK1_IN_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_CLK1_IN_P"]
set_property  PACKAGE_PIN AE24          [get_ports "FMC2_CLK1_IN_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_CLK1_IN_N"]

set_property  PACKAGE_PIN T21           [get_ports "FMC2_CLK_DIR"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC2_CLK_DIR"]

set_property  PACKAGE_PIN AB27          [get_ports "FMC2_CLK3_IN_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_CLK3_IN_P"]
set_property  PACKAGE_PIN AC27          [get_ports "FMC2_CLK3_IN_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_CLK3_IN_N"]

set_property  PACKAGE_PIN Y26           [get_ports "FMC2_CLK3_OUT_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_CLK3_OUT_P"]
set_property  PACKAGE_PIN AA26          [get_ports "FMC2_CLK3_OUT_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_CLK3_OUT_N"]

set_property  PACKAGE_PIN AF22          [get_ports "FMC2_LA_P[0]"]
set_property  PACKAGE_PIN AG23          [get_ports "FMC2_LA_N[0]"]
set_property  PACKAGE_PIN AE23          [get_ports "FMC2_LA_P[1]"]
set_property  PACKAGE_PIN AF23          [get_ports "FMC2_LA_N[1]"]
set_property  PACKAGE_PIN AG20          [get_ports "FMC2_LA_P[2]"]
set_property  PACKAGE_PIN AH20          [get_ports "FMC2_LA_N[2]"]
set_property  PACKAGE_PIN AC20          [get_ports "FMC2_LA_P[3]"]
set_property  PACKAGE_PIN AC21          [get_ports "FMC2_LA_N[3]"]
set_property  PACKAGE_PIN AH21          [get_ports "FMC2_LA_P[4]"]
set_property  PACKAGE_PIN AJ21          [get_ports "FMC2_LA_N[4]"]
set_property  PACKAGE_PIN AG22          [get_ports "FMC2_LA_P[5]"]
set_property  PACKAGE_PIN AH22          [get_ports "FMC2_LA_N[5]"]
set_property  PACKAGE_PIN AK20          [get_ports "FMC2_LA_P[6]"]
set_property  PACKAGE_PIN AK21          [get_ports "FMC2_LA_N[6]"]
set_property  PACKAGE_PIN AK23          [get_ports "FMC2_LA_P[7]"]
set_property  PACKAGE_PIN AK24          [get_ports "FMC2_LA_N[7]"]
set_property  PACKAGE_PIN AJ22          [get_ports "FMC2_LA_P[8]"]
set_property  PACKAGE_PIN AJ23          [get_ports "FMC2_LA_N[8]"]
set_property  PACKAGE_PIN AJ24          [get_ports "FMC2_LA_P[9]"]
set_property  PACKAGE_PIN AK25          [get_ports "FMC2_LA_N[9]"]
set_property  PACKAGE_PIN AD21          [get_ports "FMC2_LA_P[10]"]
set_property  PACKAGE_PIN AE21          [get_ports "FMC2_LA_N[10]"]
set_property  PACKAGE_PIN AE25          [get_ports "FMC2_LA_P[11]"]
set_property  PACKAGE_PIN AF25          [get_ports "FMC2_LA_N[11]"]
set_property  PACKAGE_PIN AG25          [get_ports "FMC2_LA_P[12]"]
set_property  PACKAGE_PIN AH25          [get_ports "FMC2_LA_N[12]"]
set_property  PACKAGE_PIN AC22          [get_ports "FMC2_LA_P[13]"]
set_property  PACKAGE_PIN AD22          [get_ports "FMC2_LA_N[13]"]
set_property  PACKAGE_PIN AC24          [get_ports "FMC2_LA_P[14]"]
set_property  PACKAGE_PIN AD24          [get_ports "FMC2_LA_N[14]"]
set_property  PACKAGE_PIN AA22          [get_ports "FMC2_LA_P[15]"]
set_property  PACKAGE_PIN AA23          [get_ports "FMC2_LA_N[15]"]
set_property  PACKAGE_PIN AB24          [get_ports "FMC2_LA_P[16]"]
set_property  PACKAGE_PIN AC25          [get_ports "FMC2_LA_N[16]"]

set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[5]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[5]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[6]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[6]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[7]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[7]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[8]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[8]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[9]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[9]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[10]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[10]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[11]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[11]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[12]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[12]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[13]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[13]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[14]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[14]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[15]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[15]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[16]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[16]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[0]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[0]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[1]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[1]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[2]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[2]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[3]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[3]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[4]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[4]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[5]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[5]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[6]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[6]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[7]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[7]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[8]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[8]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[9]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[9]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[10]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[10]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[11]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[11]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[12]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[12]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[13]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[13]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[14]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[14]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[15]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[15]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[16]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[16]"]

set_property  PACKAGE_PIN AE28          [get_ports "FMC2_LA_P[17]"]
set_property  PACKAGE_PIN AF28          [get_ports "FMC2_LA_N[17]"]
set_property  PACKAGE_PIN AD27          [get_ports "FMC2_LA_P[18]"]
set_property  PACKAGE_PIN AD28          [get_ports "FMC2_LA_N[18]"]
set_property  PACKAGE_PIN AH26          [get_ports "FMC2_LA_P[19]"]
set_property  PACKAGE_PIN AH27          [get_ports "FMC2_LA_N[19]"]
set_property  PACKAGE_PIN AJ26          [get_ports "FMC2_LA_P[20]"]
set_property  PACKAGE_PIN AK26          [get_ports "FMC2_LA_N[20]"]
set_property  PACKAGE_PIN AJ28          [get_ports "FMC2_LA_P[21]"]
set_property  PACKAGE_PIN AJ29          [get_ports "FMC2_LA_N[21]"]
set_property  PACKAGE_PIN AK29          [get_ports "FMC2_LA_P[22]"]
set_property  PACKAGE_PIN AK30          [get_ports "FMC2_LA_N[22]"]
set_property  PACKAGE_PIN AJ27          [get_ports "FMC2_LA_P[23]"]
set_property  PACKAGE_PIN AK28          [get_ports "FMC2_LA_N[23]"]
set_property  PACKAGE_PIN AE30          [get_ports "FMC2_LA_P[24]"]
set_property  PACKAGE_PIN AF30          [get_ports "FMC2_LA_N[24]"]
set_property  PACKAGE_PIN AF26          [get_ports "FMC2_LA_P[25]"]
set_property  PACKAGE_PIN AF27          [get_ports "FMC2_LA_N[25]"]
set_property  PACKAGE_PIN AG27          [get_ports "FMC2_LA_P[26]"]
set_property  PACKAGE_PIN AG28          [get_ports "FMC2_LA_N[26]"]
set_property  PACKAGE_PIN AG30          [get_ports "FMC2_LA_P[27]"]
set_property  PACKAGE_PIN AH30          [get_ports "FMC2_LA_N[27]"]
set_property  PACKAGE_PIN AC29          [get_ports "FMC2_LA_P[28]"]
set_property  PACKAGE_PIN AC30          [get_ports "FMC2_LA_N[28]"]
set_property  PACKAGE_PIN AD29          [get_ports "FMC2_LA_P[29]"]
set_property  PACKAGE_PIN AE29          [get_ports "FMC2_LA_N[29]"]
set_property  PACKAGE_PIN AA27          [get_ports "FMC2_LA_P[30]"]
set_property  PACKAGE_PIN AB28          [get_ports "FMC2_LA_N[30]"]
set_property  PACKAGE_PIN AB29          [get_ports "FMC2_LA_P[31]"]
set_property  PACKAGE_PIN AB30          [get_ports "FMC2_LA_N[31]"]
set_property  PACKAGE_PIN W29           [get_ports "FMC2_LA_P[32]"]
set_property  PACKAGE_PIN Y29           [get_ports "FMC2_LA_N[32]"]
set_property  PACKAGE_PIN Y30           [get_ports "FMC2_LA_P[33]"]
set_property  PACKAGE_PIN AA30          [get_ports "FMC2_LA_N[33]"]

set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[17]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[17]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[18]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[18]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[19]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[19]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[20]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[20]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[21]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[21]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[22]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[22]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[23]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[23]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[24]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[24]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[25]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[25]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[26]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[26]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[27]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[27]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[28]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[28]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[29]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[29]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[30]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[30]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[31]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[31]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[32]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[32]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_P[33]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_LA_N[33]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[17]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[17]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[18]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[18]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[19]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[19]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[20]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[20]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[21]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[21]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[22]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[22]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[23]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[23]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[24]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[24]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[25]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[25]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[26]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[26]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[27]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[27]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[28]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[28]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[29]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[29]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[30]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[30]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[31]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[31]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[32]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[32]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_P[33]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC2_LA_N[33]"]

# ADC channels
set_property  PACKAGE_PIN L22           [get_ports "FMC2_HB_P[0]"]
set_property  PACKAGE_PIN L23           [get_ports "FMC2_HB_N[0]"]
set_property  PACKAGE_PIN L21           [get_ports "FMC2_HB_P[1]"]
set_property  PACKAGE_PIN K21           [get_ports "FMC2_HB_N[1]"]
set_property  PACKAGE_PIN L30           [get_ports "FMC2_HB_P[2]"]
set_property  PACKAGE_PIN K30           [get_ports "FMC2_HB_N[2]"]
set_property  PACKAGE_PIN J29           [get_ports "FMC2_HB_P[3]"]
set_property  PACKAGE_PIN H29           [get_ports "FMC2_HB_N[3]"]
set_property  PACKAGE_PIN L26           [get_ports "FMC2_HB_P[4]"]
set_property  PACKAGE_PIN L27           [get_ports "FMC2_HB_N[4]"]

set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_P[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_N[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_P[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_N[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_P[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_N[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_P[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_N[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_P[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC2_HB_N[4]"]

# VP/VN
# set_property  PACKAGE_PIN R15           [get_ports "FMC2_HB_P[5]"]
# set_property  PACKAGE_PIN T14           [get_ports "FMC2_HB_N[5]"]

######################################################################
# FMC3
set_property  PACKAGE_PIN R29           [get_ports "FMC3_PRSNT_B"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC3_PRSNT_B"]

set_property  PACKAGE_PIN C25           [get_ports "FMC3_CLK1_IN_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_CLK1_IN_P"]
set_property  PACKAGE_PIN B25           [get_ports "FMC3_CLK1_IN_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_CLK1_IN_N"]

set_property  PACKAGE_PIN T20           [get_ports "FMC3_CLK_DIR"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "FMC3_CLK_DIR"]

set_property  PACKAGE_PIN F20           [get_ports "FMC3_CLK3_IN_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_CLK3_IN_P"]
set_property  PACKAGE_PIN E20           [get_ports "FMC3_CLK3_IN_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_CLK3_IN_N"]

set_property  PACKAGE_PIN K18           [get_ports "FMC3_CLK3_OUT_P"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_CLK3_OUT_P"]
set_property  PACKAGE_PIN J18           [get_ports "FMC3_CLK3_OUT_N"]
set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_CLK3_OUT_N"]

set_property  PACKAGE_PIN D27           [get_ports "FMC3_LA_P[0]"]
set_property  PACKAGE_PIN C27           [get_ports "FMC3_LA_N[0]"]
set_property  PACKAGE_PIN D26           [get_ports "FMC3_LA_P[1]"]
set_property  PACKAGE_PIN C26           [get_ports "FMC3_LA_N[1]"]
set_property  PACKAGE_PIN H30           [get_ports "FMC3_LA_P[2]"]
set_property  PACKAGE_PIN G30           [get_ports "FMC3_LA_N[2]"]
set_property  PACKAGE_PIN G29           [get_ports "FMC3_LA_P[3]"]
set_property  PACKAGE_PIN F30           [get_ports "FMC3_LA_N[3]"]
set_property  PACKAGE_PIN E29           [get_ports "FMC3_LA_P[4]"]
set_property  PACKAGE_PIN E30           [get_ports "FMC3_LA_N[4]"]
set_property  PACKAGE_PIN G28           [get_ports "FMC3_LA_P[5]"]
set_property  PACKAGE_PIN F28           [get_ports "FMC3_LA_N[5]"]
set_property  PACKAGE_PIN H26           [get_ports "FMC3_LA_P[6]"]
set_property  PACKAGE_PIN H27           [get_ports "FMC3_LA_N[6]"]
set_property  PACKAGE_PIN D29           [get_ports "FMC3_LA_P[7]"]
set_property  PACKAGE_PIN C30           [get_ports "FMC3_LA_N[7]"]
set_property  PACKAGE_PIN G27           [get_ports "FMC3_LA_P[8]"]
set_property  PACKAGE_PIN F27           [get_ports "FMC3_LA_N[8]"]
set_property  PACKAGE_PIN C29           [get_ports "FMC3_LA_P[9]"]
set_property  PACKAGE_PIN B29           [get_ports "FMC3_LA_N[9]"]
set_property  PACKAGE_PIN E24           [get_ports "FMC3_LA_P[10]"]
set_property  PACKAGE_PIN D24           [get_ports "FMC3_LA_N[10]"]
set_property  PACKAGE_PIN F26           [get_ports "FMC3_LA_P[11]"]
set_property  PACKAGE_PIN E26           [get_ports "FMC3_LA_N[11]"]
set_property  PACKAGE_PIN B30           [get_ports "FMC3_LA_P[12]"]
set_property  PACKAGE_PIN A30           [get_ports "FMC3_LA_N[12]"]
set_property  PACKAGE_PIN B27           [get_ports "FMC3_LA_P[13]"]
set_property  PACKAGE_PIN A27           [get_ports "FMC3_LA_N[13]"]
set_property  PACKAGE_PIN A25           [get_ports "FMC3_LA_P[14]"]
set_property  PACKAGE_PIN A26           [get_ports "FMC3_LA_N[14]"]
set_property  PACKAGE_PIN C24           [get_ports "FMC3_LA_P[15]"]
set_property  PACKAGE_PIN B24           [get_ports "FMC3_LA_N[15]"]
set_property  PACKAGE_PIN B28           [get_ports "FMC3_LA_P[16]"]
set_property  PACKAGE_PIN A28           [get_ports "FMC3_LA_N[16]"]

set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[5]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[5]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[6]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[6]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[7]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[7]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[8]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[8]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[9]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[9]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[10]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[10]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[11]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[11]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[12]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[12]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[13]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[13]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[14]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[14]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[15]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[15]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[16]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[16]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[0]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[0]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[1]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[1]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[2]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[2]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[3]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[3]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[4]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[4]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[5]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[5]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[6]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[6]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[7]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[7]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[8]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[8]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[9]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[9]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[10]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[10]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[11]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[11]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[12]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[12]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[13]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[13]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[14]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[14]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[15]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[15]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[16]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[16]"]

set_property  PACKAGE_PIN E19           [get_ports "FMC3_LA_P[17]"]
set_property  PACKAGE_PIN D19           [get_ports "FMC3_LA_N[17]"]
set_property  PACKAGE_PIN F21           [get_ports "FMC3_LA_P[18]"]
set_property  PACKAGE_PIN E21           [get_ports "FMC3_LA_N[18]"]
set_property  PACKAGE_PIN G22           [get_ports "FMC3_LA_P[19]"]
set_property  PACKAGE_PIN F22           [get_ports "FMC3_LA_N[19]"]
set_property  PACKAGE_PIN H21           [get_ports "FMC3_LA_P[20]"]
set_property  PACKAGE_PIN H22           [get_ports "FMC3_LA_N[20]"]
set_property  PACKAGE_PIN D22           [get_ports "FMC3_LA_P[21]"]
set_property  PACKAGE_PIN C22           [get_ports "FMC3_LA_N[21]"]
set_property  PACKAGE_PIN G17           [get_ports "FMC3_LA_P[22]"]
set_property  PACKAGE_PIN F17           [get_ports "FMC3_LA_N[22]"]
set_property  PACKAGE_PIN G18           [get_ports "FMC3_LA_P[23]"]
set_property  PACKAGE_PIN F18           [get_ports "FMC3_LA_N[23]"]
set_property  PACKAGE_PIN L17           [get_ports "FMC3_LA_P[24]"]
set_property  PACKAGE_PIN L18           [get_ports "FMC3_LA_N[24]"]
set_property  PACKAGE_PIN D21           [get_ports "FMC3_LA_P[25]"]
set_property  PACKAGE_PIN C21           [get_ports "FMC3_LA_N[25]"]
set_property  PACKAGE_PIN B22           [get_ports "FMC3_LA_P[26]"]
set_property  PACKAGE_PIN A22           [get_ports "FMC3_LA_N[26]"]
set_property  PACKAGE_PIN J19           [get_ports "FMC3_LA_P[27]"]
set_property  PACKAGE_PIN H19           [get_ports "FMC3_LA_N[27]"]
set_property  PACKAGE_PIN C19           [get_ports "FMC3_LA_P[28]"]
set_property  PACKAGE_PIN B19           [get_ports "FMC3_LA_N[28]"]
set_property  PACKAGE_PIN A20           [get_ports "FMC3_LA_P[29]"]
set_property  PACKAGE_PIN A21           [get_ports "FMC3_LA_N[29]"]
set_property  PACKAGE_PIN C17           [get_ports "FMC3_LA_P[30]"]
set_property  PACKAGE_PIN B17           [get_ports "FMC3_LA_N[30]"]
set_property  PACKAGE_PIN B18           [get_ports "FMC3_LA_P[31]"]
set_property  PACKAGE_PIN A18           [get_ports "FMC3_LA_N[31]"]
set_property  PACKAGE_PIN D16           [get_ports "FMC3_LA_P[32]"]
set_property  PACKAGE_PIN C16           [get_ports "FMC3_LA_N[32]"]
set_property  PACKAGE_PIN A16           [get_ports "FMC3_LA_P[33]"]
set_property  PACKAGE_PIN A17           [get_ports "FMC3_LA_N[33]"]

set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[17]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[17]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[18]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[18]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[19]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[19]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[20]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[20]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[21]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[21]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[22]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[22]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[23]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[23]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[24]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[24]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[25]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[25]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[26]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[26]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[27]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[27]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[28]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[28]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[29]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[29]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[30]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[30]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[31]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[31]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[32]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[32]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_P[33]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_LA_N[33]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[17]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[17]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[18]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[18]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[19]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[19]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[20]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[20]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[21]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[21]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[22]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[22]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[23]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[23]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[24]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[24]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[25]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[25]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[26]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[26]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[27]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[27]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[28]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[28]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[29]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[29]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[30]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[30]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[31]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[31]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[32]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[32]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_P[33]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_LA_N[33]"]

set_property  PACKAGE_PIN G13           [get_ports "FMC3_HA_P[0]"]
set_property  PACKAGE_PIN F13           [get_ports "FMC3_HA_N[0]"]
set_property  PACKAGE_PIN H14           [get_ports "FMC3_HA_P[1]"]
set_property  PACKAGE_PIN G14           [get_ports "FMC3_HA_N[1]"]
set_property  PACKAGE_PIN L15           [get_ports "FMC3_HA_P[2]"]
set_property  PACKAGE_PIN K15           [get_ports "FMC3_HA_N[2]"]
set_property  PACKAGE_PIN L16           [get_ports "FMC3_HA_P[3]"]
set_property  PACKAGE_PIN K16           [get_ports "FMC3_HA_N[3]"]
set_property  PACKAGE_PIN L11           [get_ports "FMC3_HA_P[4]"]
set_property  PACKAGE_PIN K11           [get_ports "FMC3_HA_N[4]"]
set_property  PACKAGE_PIN L12           [get_ports "FMC3_HA_P[5]"]
set_property  PACKAGE_PIN L13           [get_ports "FMC3_HA_N[5]"]
set_property  PACKAGE_PIN K14           [get_ports "FMC3_HA_P[6]"]
set_property  PACKAGE_PIN J14           [get_ports "FMC3_HA_N[6]"]
set_property  PACKAGE_PIN J16           [get_ports "FMC3_HA_P[7]"]
set_property  PACKAGE_PIN H16           [get_ports "FMC3_HA_N[7]"]
set_property  PACKAGE_PIN J11           [get_ports "FMC3_HA_P[8]"]
set_property  PACKAGE_PIN J12           [get_ports "FMC3_HA_N[8]"]
set_property  PACKAGE_PIN K13           [get_ports "FMC3_HA_P[9]"]
set_property  PACKAGE_PIN J13           [get_ports "FMC3_HA_N[9]"]
set_property  PACKAGE_PIN F15           [get_ports "FMC3_HA_P[10]"]
set_property  PACKAGE_PIN E16           [get_ports "FMC3_HA_N[10]"]
set_property  PACKAGE_PIN H15           [get_ports "FMC3_HA_P[11]"]
set_property  PACKAGE_PIN G15           [get_ports "FMC3_HA_N[11]"]
set_property  PACKAGE_PIN C15           [get_ports "FMC3_HA_P[12]"]
set_property  PACKAGE_PIN B15           [get_ports "FMC3_HA_N[12]"]
set_property  PACKAGE_PIN H11           [get_ports "FMC3_HA_P[13]"]
set_property  PACKAGE_PIN H12           [get_ports "FMC3_HA_N[13]"]
set_property  PACKAGE_PIN E14           [get_ports "FMC3_HA_P[14]"]
set_property  PACKAGE_PIN E15           [get_ports "FMC3_HA_N[14]"]
set_property  PACKAGE_PIN F11           [get_ports "FMC3_HA_P[15]"]
set_property  PACKAGE_PIN E11           [get_ports "FMC3_HA_N[15]"]
set_property  PACKAGE_PIN D14           [get_ports "FMC3_HA_P[16]"]
set_property  PACKAGE_PIN C14           [get_ports "FMC3_HA_N[16]"]
set_property  PACKAGE_PIN D12           [get_ports "FMC3_HA_P[17]"]
set_property  PACKAGE_PIN D13           [get_ports "FMC3_HA_N[17]"]
set_property  PACKAGE_PIN F12           [get_ports "FMC3_HA_P[18]"]
set_property  PACKAGE_PIN E13           [get_ports "FMC3_HA_N[18]"]
set_property  PACKAGE_PIN D11           [get_ports "FMC3_HA_P[19]"]
set_property  PACKAGE_PIN C11           [get_ports "FMC3_HA_N[19]"]
set_property  PACKAGE_PIN C12           [get_ports "FMC3_HA_P[20]"]
set_property  PACKAGE_PIN B12           [get_ports "FMC3_HA_N[20]"]
set_property  PACKAGE_PIN B14           [get_ports "FMC3_HA_P[21]"]
set_property  PACKAGE_PIN A15           [get_ports "FMC3_HA_N[21]"]
set_property  PACKAGE_PIN B13           [get_ports "FMC3_HA_P[22]"]
set_property  PACKAGE_PIN A13           [get_ports "FMC3_HA_N[22]"]
set_property  PACKAGE_PIN A11           [get_ports "FMC3_HA_P[23]"]
set_property  PACKAGE_PIN A12           [get_ports "FMC3_HA_N[23]"]

set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[5]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[5]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[6]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[6]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[7]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[7]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[8]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[8]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[9]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[9]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[10]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[10]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[11]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[11]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[12]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[12]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[13]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[13]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[14]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[14]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[15]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[15]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[16]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[16]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[17]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[17]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[18]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[18]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[19]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[19]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[20]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[20]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[21]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[21]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[22]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[22]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_P[23]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HA_N[23]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[0]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[0]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[1]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[1]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[2]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[2]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[3]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[3]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[4]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[4]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[5]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[5]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[6]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[6]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[7]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[7]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[8]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[8]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[9]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[9]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[10]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[10]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[11]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[11]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[12]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[12]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[13]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[13]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[14]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[14]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[15]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[15]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[16]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[16]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[17]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[17]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[18]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[18]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[19]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[19]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[20]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[20]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[21]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[21]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[22]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[22]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_P[23]"]
# set_property  IOSTANDARD  LVDS_25       [get_ports "FMC3_HA_N[23]"]

# ADC channels
set_property  PACKAGE_PIN J23           [get_ports "FMC3_HB_P[0]"]
set_property  PACKAGE_PIN J24           [get_ports "FMC3_HB_N[0]"]
set_property  PACKAGE_PIN K23           [get_ports "FMC3_HB_P[1]"]
set_property  PACKAGE_PIN K24           [get_ports "FMC3_HB_N[1]"]
set_property  PACKAGE_PIN L25           [get_ports "FMC3_HB_P[2]"]
set_property  PACKAGE_PIN K25           [get_ports "FMC3_HB_N[2]"]
set_property  PACKAGE_PIN J21           [get_ports "FMC3_HB_P[3]"]
set_property  PACKAGE_PIN J22           [get_ports "FMC3_HB_N[3]"]
set_property  PACKAGE_PIN K26           [get_ports "FMC3_HB_P[4]"]
set_property  PACKAGE_PIN J26           [get_ports "FMC3_HB_N[4]"]
set_property  PACKAGE_PIN J27           [get_ports "FMC3_HB_P[5]"]
set_property  PACKAGE_PIN J28           [get_ports "FMC3_HB_N[5]"]

set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_P[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_N[0]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_P[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_N[1]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_P[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_N[2]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_P[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_N[3]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_P[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_N[4]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_P[5]"]
set_property  IOSTANDARD  LVCMOS25      [get_ports "FMC3_HB_N[5]"]

######################################################################
# DDR3
set_property  PACKAGE_PIN AD12          [get_ports "DDR3_CK_P[0]"]
set_property  PACKAGE_PIN AD11          [get_ports "DDR3_CK_N[0]"]
set_property  PACKAGE_PIN AE11          [get_ports "DDR3_CK_P[1]"]
set_property  PACKAGE_PIN AF11          [get_ports "DDR3_CK_N[1]"]
set_property  PACKAGE_PIN AC12          [get_ports "DDR3_CKE[0]"]
set_property  PACKAGE_PIN AC10          [get_ports "DDR3_CKE[1]"]
set_property  PACKAGE_PIN AH9           [get_ports "DDR3_CS_N[0]"]
set_property  PACKAGE_PIN AD8           [get_ports "DDR3_CS_N[1]"]
set_property  PACKAGE_PIN AE10          [get_ports "DDR3_ODT[0]"]
set_property  PACKAGE_PIN AE8           [get_ports "DDR3_ODT[1]"]
set_property  PACKAGE_PIN AH12          [get_ports "DDR3_ADDR[0]"]
set_property  PACKAGE_PIN AK11          [get_ports "DDR3_ADDR[1]"]
set_property  PACKAGE_PIN AK10          [get_ports "DDR3_ADDR[2]"]
set_property  PACKAGE_PIN AJ11          [get_ports "DDR3_ADDR[3]"]
set_property  PACKAGE_PIN AJ12          [get_ports "DDR3_ADDR[4]"]
set_property  PACKAGE_PIN AG12          [get_ports "DDR3_ADDR[5]"]
set_property  PACKAGE_PIN AG13          [get_ports "DDR3_ADDR[6]"]
set_property  PACKAGE_PIN AK13          [get_ports "DDR3_ADDR[7]"]
set_property  PACKAGE_PIN AJ13          [get_ports "DDR3_ADDR[8]"]
set_property  PACKAGE_PIN AJ14          [get_ports "DDR3_ADDR[9]"]
set_property  PACKAGE_PIN AH11          [get_ports "DDR3_ADDR[10]"]
set_property  PACKAGE_PIN AH14          [get_ports "DDR3_ADDR[11]"]
set_property  PACKAGE_PIN AK14          [get_ports "DDR3_ADDR[12]"]
set_property  PACKAGE_PIN AF12          [get_ports "DDR3_ADDR[13]"]
set_property  PACKAGE_PIN AE13          [get_ports "DDR3_ADDR[14]"]
set_property  PACKAGE_PIN AB10          [get_ports "DDR3_ADDR[15]"]
set_property  PACKAGE_PIN AG9           [get_ports "DDR3_BA[0]"]
set_property  PACKAGE_PIN AF10          [get_ports "DDR3_BA[1]"]
set_property  PACKAGE_PIN AC11          [get_ports "DDR3_BA[2]"]
set_property  PACKAGE_PIN AK9           [get_ports "DDR3_RAS_N"]
set_property  PACKAGE_PIN AD9           [get_ports "DDR3_CAS_N"]
set_property  PACKAGE_PIN AE9           [get_ports "DDR3_WE_N"]
set_property  PACKAGE_PIN AJ9           [get_ports "DDR3_RESET_N"]
set_property  PACKAGE_PIN AK3           [get_ports "DDR3_TEMP_EVENT"]
set_property  PACKAGE_PIN Y15           [get_ports "DDR3_DQ[0]"]
set_property  PACKAGE_PIN Y16           [get_ports "DDR3_DQ[1]"]
set_property  PACKAGE_PIN AA17          [get_ports "DDR3_DQ[2]"]
set_property  PACKAGE_PIN AA15          [get_ports "DDR3_DQ[3]"]
set_property  PACKAGE_PIN AB15          [get_ports "DDR3_DQ[4]"]
set_property  PACKAGE_PIN AC14          [get_ports "DDR3_DQ[5]"]
set_property  PACKAGE_PIN AD14          [get_ports "DDR3_DQ[6]"]
set_property  PACKAGE_PIN AE15          [get_ports "DDR3_DQ[7]"]
set_property  PACKAGE_PIN AD18          [get_ports "DDR3_DQ[8]"]
set_property  PACKAGE_PIN AE18          [get_ports "DDR3_DQ[9]"]
set_property  PACKAGE_PIN AD17          [get_ports "DDR3_DQ[10]"]
set_property  PACKAGE_PIN AD16          [get_ports "DDR3_DQ[11]"]
set_property  PACKAGE_PIN AB19          [get_ports "DDR3_DQ[12]"]
set_property  PACKAGE_PIN AB18          [get_ports "DDR3_DQ[13]"]
set_property  PACKAGE_PIN AB17          [get_ports "DDR3_DQ[14]"]
set_property  PACKAGE_PIN AA18          [get_ports "DDR3_DQ[15]"]
set_property  PACKAGE_PIN AJ19          [get_ports "DDR3_DQ[16]"]
set_property  PACKAGE_PIN AK19          [get_ports "DDR3_DQ[17]"]
set_property  PACKAGE_PIN AF18          [get_ports "DDR3_DQ[18]"]
set_property  PACKAGE_PIN AF17          [get_ports "DDR3_DQ[19]"]
set_property  PACKAGE_PIN AG19          [get_ports "DDR3_DQ[20]"]
set_property  PACKAGE_PIN AE19          [get_ports "DDR3_DQ[21]"]
set_property  PACKAGE_PIN AD19          [get_ports "DDR3_DQ[22]"]
set_property  PACKAGE_PIN AG18          [get_ports "DDR3_DQ[23]"]
set_property  PACKAGE_PIN AK16          [get_ports "DDR3_DQ[24]"]
set_property  PACKAGE_PIN AJ17          [get_ports "DDR3_DQ[25]"]
set_property  PACKAGE_PIN AK15          [get_ports "DDR3_DQ[26]"]
set_property  PACKAGE_PIN AH15          [get_ports "DDR3_DQ[27]"]
set_property  PACKAGE_PIN AE16          [get_ports "DDR3_DQ[28]"]
set_property  PACKAGE_PIN AH17          [get_ports "DDR3_DQ[29]"]
set_property  PACKAGE_PIN AG15          [get_ports "DDR3_DQ[30]"]
set_property  PACKAGE_PIN AG14          [get_ports "DDR3_DQ[31]"]
set_property  PACKAGE_PIN AK8           [get_ports "DDR3_DQ[32]"]
set_property  PACKAGE_PIN AJ8           [get_ports "DDR3_DQ[33]"]
set_property  PACKAGE_PIN AK6           [get_ports "DDR3_DQ[34]"]
set_property  PACKAGE_PIN AK5           [get_ports "DDR3_DQ[35]"]
set_property  PACKAGE_PIN AG7           [get_ports "DDR3_DQ[36]"]
set_property  PACKAGE_PIN AF8           [get_ports "DDR3_DQ[37]"]
set_property  PACKAGE_PIN AF7           [get_ports "DDR3_DQ[38]"]
set_property  PACKAGE_PIN AK4           [get_ports "DDR3_DQ[39]"]
set_property  PACKAGE_PIN AK1           [get_ports "DDR3_DQ[40]"]
set_property  PACKAGE_PIN AJ3           [get_ports "DDR3_DQ[41]"]
set_property  PACKAGE_PIN AJ1           [get_ports "DDR3_DQ[42]"]
set_property  PACKAGE_PIN AH2           [get_ports "DDR3_DQ[43]"]
set_property  PACKAGE_PIN AH4           [get_ports "DDR3_DQ[44]"]
set_property  PACKAGE_PIN AJ4           [get_ports "DDR3_DQ[45]"]
set_property  PACKAGE_PIN AH5           [get_ports "DDR3_DQ[46]"]
set_property  PACKAGE_PIN AH6           [get_ports "DDR3_DQ[47]"]
set_property  PACKAGE_PIN AF3           [get_ports "DDR3_DQ[48]"]
set_property  PACKAGE_PIN AF2           [get_ports "DDR3_DQ[49]"]
set_property  PACKAGE_PIN AE3           [get_ports "DDR3_DQ[50]"]
set_property  PACKAGE_PIN AE1           [get_ports "DDR3_DQ[51]"]
set_property  PACKAGE_PIN AF6           [get_ports "DDR3_DQ[52]"]
set_property  PACKAGE_PIN AE5           [get_ports "DDR3_DQ[53]"]
set_property  PACKAGE_PIN AE4           [get_ports "DDR3_DQ[54]"]
set_property  PACKAGE_PIN AF1           [get_ports "DDR3_DQ[55]"]
set_property  PACKAGE_PIN AE6           [get_ports "DDR3_DQ[56]"]
set_property  PACKAGE_PIN AC5           [get_ports "DDR3_DQ[57]"]
set_property  PACKAGE_PIN AC4           [get_ports "DDR3_DQ[58]"]
set_property  PACKAGE_PIN AD3           [get_ports "DDR3_DQ[59]"]
set_property  PACKAGE_PIN AD6           [get_ports "DDR3_DQ[60]"]
set_property  PACKAGE_PIN AC7           [get_ports "DDR3_DQ[61]"]
set_property  PACKAGE_PIN AC1           [get_ports "DDR3_DQ[62]"]
set_property  PACKAGE_PIN AC2           [get_ports "DDR3_DQ[63]"]
set_property  PACKAGE_PIN AA16          [get_ports "DDR3_DM[0]"]
set_property  PACKAGE_PIN AC19          [get_ports "DDR3_DM[1]"]
set_property  PACKAGE_PIN AH19          [get_ports "DDR3_DM[2]"]
set_property  PACKAGE_PIN AF15          [get_ports "DDR3_DM[3]"]
set_property  PACKAGE_PIN AJ6           [get_ports "DDR3_DM[4]"]
set_property  PACKAGE_PIN AJ2           [get_ports "DDR3_DM[5]"]
set_property  PACKAGE_PIN AF5           [get_ports "DDR3_DM[6]"]
set_property  PACKAGE_PIN AD4           [get_ports "DDR3_DM[7]"]
set_property  PACKAGE_PIN AC16          [get_ports "DDR3_DQS_P[0]"]
set_property  PACKAGE_PIN AC15          [get_ports "DDR3_DQS_N[0]"]
set_property  PACKAGE_PIN Y19           [get_ports "DDR3_DQS_P[1]"]
set_property  PACKAGE_PIN Y18           [get_ports "DDR3_DQS_N[1]"]
set_property  PACKAGE_PIN AJ18          [get_ports "DDR3_DQS_P[2]"]
set_property  PACKAGE_PIN AK18          [get_ports "DDR3_DQS_N[2]"]
set_property  PACKAGE_PIN AH16          [get_ports "DDR3_DQS_P[3]"]
set_property  PACKAGE_PIN AJ16          [get_ports "DDR3_DQS_N[3]"]
set_property  PACKAGE_PIN AH7           [get_ports "DDR3_DQS_P[4]"]
set_property  PACKAGE_PIN AJ7           [get_ports "DDR3_DQS_N[4]"]
set_property  PACKAGE_PIN AG2           [get_ports "DDR3_DQS_P[5]"]
set_property  PACKAGE_PIN AH1           [get_ports "DDR3_DQS_N[5]"]
set_property  PACKAGE_PIN AG4           [get_ports "DDR3_DQS_P[6]"]
set_property  PACKAGE_PIN AG3           [get_ports "DDR3_DQS_N[6]"]
set_property  PACKAGE_PIN AD2           [get_ports "DDR3_DQS_P[7]"]
set_property  PACKAGE_PIN AD1           [get_ports "DDR3_DQS_N[7]"]

set_property  IOSTANDARD  DIFF_SSTL135  [get_ports "DDR3_CK_P[*]"]
set_property  IOSTANDARD  DIFF_SSTL135  [get_ports "DDR3_CK_N[*]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_CKE[*]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_CS_N[*]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_ODT[*]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_ADDR[*]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_BA[*]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_RAS_N"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_CAS_N"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_WE_N"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_RESET_N"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_TEMP_EVENT"]
set_property  IOSTANDARD  SSTL135_T_DCI [get_ports "DDR3_DQ[*]"]
set_property  IOSTANDARD  SSTL135       [get_ports "DDR3_DM[*]"]
set_property  IOSTANDARD  DIFF_SSTL135_T_DCI  [get_ports "DDR3_DQS_P[*]"]
set_property  IOSTANDARD  DIFF_SSTL135_T_DCI  [get_ports "DDR3_DQS_N[*]"]

set_property  DCI_CASCADE {32 34} [get_iobanks 33]

######################################################################
# Gigabit Ethernet PHY - RGMII
set_property  PACKAGE_PIN L28           [get_ports "PHY_CLK"]

set_property  PACKAGE_PIN N25           [get_ports "PHY_TX_CLK"]
set_property  PACKAGE_PIN N26           [get_ports "PHY_TX_CTRL"]
set_property  PACKAGE_PIN N27           [get_ports "PHY_TX_D[0]"]
set_property  PACKAGE_PIN M27           [get_ports "PHY_TX_D[1]"]
set_property  PACKAGE_PIN N29           [get_ports "PHY_TX_D[2]"]
set_property  PACKAGE_PIN N30           [get_ports "PHY_TX_D[3]"]

set_property  PACKAGE_PIN M28           [get_ports "PHY_RX_CLK"]
set_property  PACKAGE_PIN M29           [get_ports "PHY_RX_CTRL"]
set_property  PACKAGE_PIN N22           [get_ports "PHY_RX_D[0]"]
set_property  PACKAGE_PIN N21           [get_ports "PHY_RX_D[1]"]
set_property  PACKAGE_PIN N20           [get_ports "PHY_RX_D[2]"]
set_property  PACKAGE_PIN N19           [get_ports "PHY_RX_D[3]"]

set_property  PACKAGE_PIN P23           [get_ports "PHY_GPIO[0]"]
set_property  PACKAGE_PIN N24           [get_ports "PHY_GPIO[1]"]
set_property  PACKAGE_PIN M24           [get_ports "PHY_PWDN_B"]
set_property  PACKAGE_PIN M25           [get_ports "PHY_RST_B"]

set_property  PACKAGE_PIN P21           [get_ports "PHY_MDC"]
set_property  PACKAGE_PIN P22           [get_ports "PHY_MDIO"]

set_property  IOSTANDARD  LVCMOS25 		[get_ports "PHY_*"]

######################################################################
# FireFly
# set_property  PACKAGE_PIN K2            [get_ports "TX117_P[0]"]
# set_property  PACKAGE_PIN J4            [get_ports "TX117_P[1]"]
# set_property  PACKAGE_PIN H2            [get_ports "TX117_P[2]"]
# set_property  PACKAGE_PIN F2            [get_ports "TX117_P[3]"]
# set_property  PACKAGE_PIN K6            [get_ports "RX117_P[0]"]
# set_property  PACKAGE_PIN H6            [get_ports "RX117_P[1]"]
# set_property  PACKAGE_PIN G4            [get_ports "RX117_P[2]"]
# set_property  PACKAGE_PIN F6            [get_ports "RX117_P[3]"]

# set_property  PACKAGE_PIN G8            [get_ports "MGTCLK117_P0"]
# set_property  PACKAGE_PIN J8            [get_ports "MGTCLK117_P1"]

set_property  PACKAGE_PIN V19           [get_ports "MODPRSL117"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MODPRSL117"]
set_property  PACKAGE_PIN V20           [get_ports "MODSEL117"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MODSEL117"]
set_property  PACKAGE_PIN W21           [get_ports "INTL117"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "INTL117"]
set_property  PACKAGE_PIN W22           [get_ports "RESETL117"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RESETL117"]


# set_property  PACKAGE_PIN D2            [get_ports "TX118_P[0]"]
# set_property  PACKAGE_PIN C4            [get_ports "TX118_P[1]"]
# set_property  PACKAGE_PIN B2            [get_ports "TX118_P[2]"]
# set_property  PACKAGE_PIN A4            [get_ports "TX118_P[3]"]
# set_property  PACKAGE_PIN E4            [get_ports "RX118_P[0]"]
# set_property  PACKAGE_PIN D6            [get_ports "RX118_P[1]"]
# set_property  PACKAGE_PIN B6            [get_ports "RX118_P[2]"]
# set_property  PACKAGE_PIN A8            [get_ports "RX118_P[3]"]

# set_property  PACKAGE_PIN C8            [get_ports "MGTCLK118_P0"]
# set_property  PACKAGE_PIN E8            [get_ports "MGTCLK118_P1"]

set_property  PACKAGE_PIN T22           [get_ports "MODPRSL118"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MODPRSL118"]
set_property  PACKAGE_PIN T23           [get_ports "MODSEL118"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "MODSEL118"]
set_property  PACKAGE_PIN P26           [get_ports "INTL118"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "INTL118"]
set_property  PACKAGE_PIN R26           [get_ports "RESETL118"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RESETL118"]

######################################################################
# MMCX
# set_property  PACKAGE_PIN P2            [get_ports "TX116_P[0]"]
# set_property  PACKAGE_PIN N4            [get_ports "TX116_P[1]"]
# set_property  PACKAGE_PIN M2            [get_ports "TX116_P[2]"]
# set_property  PACKAGE_PIN L4            [get_ports "TX116_P[3]"]
# set_property  PACKAGE_PIN T6            [get_ports "RX116_P[0]"]
# set_property  PACKAGE_PIN R4            [get_ports "RX116_P[1]"]
# set_property  PACKAGE_PIN P6            [get_ports "RX116_P[2]"]
# set_property  PACKAGE_PIN M6            [get_ports "RX116_P[3]"]

# set_property  PACKAGE_PIN L8            [get_ports "MGTCLK116_P0"]
# set_property  PACKAGE_PIN N8            [get_ports "MGTCLK116_P1"]

######################################################################
# RTM
# set_property  PACKAGE_PIN Y2            [get_ports "RTM2AMC_P[16]"]
# set_property  PACKAGE_PIN V2            [get_ports "RTM2AMC_P[17]"]
# set_property  PACKAGE_PIN U4            [get_ports "RTM2AMC_P[18]"]
# set_property  PACKAGE_PIN T2            [get_ports "RTM2AMC_P[19]"]

# set_property  PACKAGE_PIN AA4           [get_ports "AMC2RTM_P[16]"]
# set_property  PACKAGE_PIN Y6            [get_ports "AMC2RTM_P[17]"]
# set_property  PACKAGE_PIN W4            [get_ports "AMC2RTM_P[18]"]
# set_property  PACKAGE_PIN V6            [get_ports "AMC2RTM_P[19]"]

# set_property  PACKAGE_PIN R8            [get_ports "MGTCLK115_P0"]
# set_property  PACKAGE_PIN U8            [get_ports "MGTCLK115_P1"]

set_property  PACKAGE_PIN U28           [get_ports "RTM_IO[0]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RTM_IO[0]"]
set_property  PACKAGE_PIN U27           [get_ports "RTM_IO[1]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RTM_IO[1]"]
set_property  PACKAGE_PIN T25           [get_ports "RTM_IO[2]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RTM_IO[2]"]
set_property  PACKAGE_PIN U25           [get_ports "RTM_IO[3]"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RTM_IO[3]"]

set_property  PACKAGE_PIN U29           [get_ports "RTM_MODE"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RTM_MODE"]
set_property  PACKAGE_PIN U30           [get_ports "RTM_INTL"]
set_property  IOSTANDARD  LVCMOS33      [get_ports "RTM_INTL"]
