##############################################################################
# uFCP4 XCKU15P-2FFVE1517E Rev1.0 XDC 08/08/2020
set_property  SEVERITY {Warning} [get_drc_checks UCIO-1]
set_property  SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property  BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

##############################################################################
# CLK input

# Local clk 200 MHz, has 100 Ohm external termination resistor
set_property PACKAGE_PIN F13 [get_ports "CLK_IN_200_P"]
set_property PACKAGE_PIN F12 [get_ports "CLK_IN_200_N"]
set_property IOSTANDARD LVDS_25 [get_ports "CLK_IN_200_P"]
set_property IOSTANDARD LVDS_25 [get_ports "CLK_IN_200_N"]
create_clock -period 5.000 -name "CLK200" [get_ports "CLK_IN_200_P"]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets IBUFDS_clk200/O]

# clk from out1 of pll1, , has 100 Ohm external termination resistor
# share io bank with FMC0
set_property PACKAGE_PIN AU32 [get_ports "CLK_IN_PL_P"]
set_property PACKAGE_PIN AU33 [get_ports "CLK_IN_PL_N"]
# 1.0V: DIFF_POD10
# 1.2V: DIFF_HSUL_12
# 1.5V: DIFF_SSTL15
# 1.8V: LVDS
set_property IOSTANDARD LVDS [get_ports "CLK_IN_PL_P"]
set_property IOSTANDARD LVDS [get_ports "CLK_IN_PL_N"]
create_clock -period 6.400 -name "CLK_IN_PL" [get_ports "CLK_IN_PL_P"]

# clk from out8 of clk mux, has 100 Ohm external termination resistor
# share io bank with FMC1
set_property PACKAGE_PIN AK32 [get_ports "CLK_IN_SW_P"]
set_property PACKAGE_PIN AL32 [get_ports "CLK_IN_SW_N"]
# 1.0V: DIFF_POD10
# 1.2V: DIFF_HSUL_12
# 1.5V: DIFF_SSTL15
# 1.8V: LVDS
set_property IOSTANDARD LVDS [get_ports "CLK_IN_SW_P"]
set_property IOSTANDARD LVDS [get_ports "CLK_IN_SW_N"]
create_clock -period 8.000 -name "CLK_IN_SW" [get_ports "CLK_IN_SW_P"]

# CLK output

# clk output to input7 of clk mux, has 100 Ohm external termination resistor
# share io bank with FMC0
set_property PACKAGE_PIN AU28 [get_ports "CLK_OUT_P"]
set_property PACKAGE_PIN AV28 [get_ports "CLK_OUT_N"]
# 1.0V: DIFF_POD10
# 1.2V: DIFF_HSUL_12
# 1.5V: DIFF_SSTL15
# 1.8V: LVDS
set_property IOSTANDARD LVDS [get_ports "CLK_OUT_P"]
set_property IOSTANDARD LVDS [get_ports "CLK_OUT_N"]

##############################################################################
# IO

# reset_b from MCU
set_property PACKAGE_PIN C9 [get_ports "RST_B"]
set_property IOSTANDARD LVCMOS33 [get_ports "RST_B"]

# external lemo input, has 100 Ohm external termination resistor
set_property PACKAGE_PIN G12 [get_ports "LEMO_IN_P"]
set_property PACKAGE_PIN G11 [get_ports "LEMO_IN_N"]
set_property IOSTANDARD LVDS_25 [get_ports "LEMO_IN_P"]
set_property IOSTANDARD LVDS_25 [get_ports "LEMO_IN_N"]
# create_clock  -period 25.000 -name "LEMO_IN"  [get_ports "LEMO_IN_P"]

# external lemo inout, has 100 Ohm external termination resistor
set_property PACKAGE_PIN E13 [get_ports "MMCX_TEST_P"]
set_property PACKAGE_PIN D13 [get_ports "MMCX_TEST_N"]
# set_property IOSTANDARD LVDS_25 [get_ports "MMCX_TEST_P"]
# set_property IOSTANDARD LVDS_25 [get_ports "MMCX_TEST_N"]
# if use as single end, remove R250
set_property IOSTANDARD LVCMOS25 [get_ports "MMCX_TEST_P"]
set_property IOSTANDARD LVCMOS25 [get_ports "MMCX_TEST_N"]

set_property PACKAGE_PIN H12  [get_ports "TESTPIN[0]"]
set_property PACKAGE_PIN H13  [get_ports "TESTPIN[1]"]
set_property PACKAGE_PIN J12  [get_ports "TESTPIN[2]"]
set_property PACKAGE_PIN J13  [get_ports "TESTPIN[3]"]
set_property IOSTANDARD LVCMOS25 [get_ports "TESTPIN[*]"]

# On = low
set_property PACKAGE_PIN B14  [get_ports "DIPSW[7]"]
set_property PACKAGE_PIN A14  [get_ports "DIPSW[6]"]
set_property PACKAGE_PIN C13  [get_ports "DIPSW[5]"]
set_property PACKAGE_PIN A13  [get_ports "DIPSW[4]"]
set_property PACKAGE_PIN B12  [get_ports "DIPSW[3]"]
set_property PACKAGE_PIN A12  [get_ports "DIPSW[2]"]
set_property PACKAGE_PIN C12  [get_ports "DIPSW[1]"]
set_property PACKAGE_PIN D12  [get_ports "DIPSW[0]"]
set_property IOSTANDARD LVCMOS25 [get_ports "DIPSW[*]"]
set_property PULLUP     true     [get_ports "DIPSW[*]"]

# RED, low active
set_property PACKAGE_PIN C8   [get_ports "RLED_B"]
set_property IOSTANDARD LVCMOS33 [get_ports "RLED_B"]
# Blue, low active
set_property PACKAGE_PIN C10  [get_ports "BLED_B"]
set_property IOSTANDARD LVCMOS33 [get_ports "BLED_B"]
# Green, low active
set_property PACKAGE_PIN C7   [get_ports "GLED_B"]
set_property IOSTANDARD LVCMOS33 [get_ports "GLED_B"]

# Debug
set_property PACKAGE_PIN K10  [get_ports "TP24"]
set_property IOSTANDARD LVCMOS33 [get_ports "TP24"]

##############################################################################
# I2C
set_property PACKAGE_PIN D5 [get_ports "FPGA_SCL"]
set_property PACKAGE_PIN D6 [get_ports "FPGA_SDA"]
set_property IOSTANDARD LVCMOS33 [get_ports "FPGA_SCL"]
set_property IOSTANDARD LVCMOS33 [get_ports "FPGA_SDA"]
set_property PULLUP     true     [get_ports "FPGA_SCL"]
set_property PULLUP     true     [get_ports "FPGA_SDA"]

##############################################################################
# UART
set_property PACKAGE_PIN D7 [get_ports "UART_TX"]
set_property PACKAGE_PIN D8 [get_ports "UART_RX"]
set_property IOSTANDARD LVCMOS33 [get_ports "UART_TX"]
set_property IOSTANDARD LVCMOS33 [get_ports "UART_RX"]

##############################################################################
# DDR4 A
set_property PACKAGE_PIN B20 [get_ports "C0_DDR4_RESET_B"]
set_property PACKAGE_PIN A21 [get_ports "C0_DDR4_ACT_B"]
set_property PACKAGE_PIN B24 [get_ports "C0_DDR4_CK_T[1]"]
set_property PACKAGE_PIN B25 [get_ports "C0_DDR4_CK_C[1]"]
set_property PACKAGE_PIN A23 [get_ports "C0_DDR4_CK_T[0]"]
set_property PACKAGE_PIN A24 [get_ports "C0_DDR4_CK_C[0]"]
set_property PACKAGE_PIN B21 [get_ports "C0_DDR4_CKE[1]"]
set_property PACKAGE_PIN C20 [get_ports "C0_DDR4_CKE[0]"]
set_property PACKAGE_PIN D23 [get_ports "C0_DDR4_ODT[1]"]
set_property PACKAGE_PIN C22 [get_ports "C0_DDR4_ODT[0]"]
# set_property PACKAGE_PIN C23 [get_ports "C0_DDR4_PARITY"]
# set_property PACKAGE_PIN A22 [get_ports "C0_DDR4_EVENT_B"]
# set_property PACKAGE_PIN B22 [get_ports "C0_DDR4_ALERT_B"]
# set_property PACKAGE_PIN E25 [get_ports "C0_DDR4_CS_B[3]"]
# set_property PACKAGE_PIN H24 [get_ports "C0_DDR4_CS_B[2]"]
set_property PACKAGE_PIN C25 [get_ports "C0_DDR4_CS_B[1]"]
set_property PACKAGE_PIN E24 [get_ports "C0_DDR4_CS_B[0]"]
set_property PACKAGE_PIN E23 [get_ports "C0_DDR4_BA[1]"]
set_property PACKAGE_PIN F24 [get_ports "C0_DDR4_BA[0]"]
set_property PACKAGE_PIN J22 [get_ports "C0_DDR4_BG[1]"]
set_property PACKAGE_PIN J21 [get_ports "C0_DDR4_BG[0]"]
set_property PACKAGE_PIN G22 [get_ports "C0_DDR4_ADDR[16]"]
set_property PACKAGE_PIN F23 [get_ports "C0_DDR4_ADDR[15]"]
set_property PACKAGE_PIN C24 [get_ports "C0_DDR4_ADDR[14]"]
set_property PACKAGE_PIN G24 [get_ports "C0_DDR4_ADDR[13]"]
set_property PACKAGE_PIN H22 [get_ports "C0_DDR4_ADDR[12]"]
set_property PACKAGE_PIN F21 [get_ports "C0_DDR4_ADDR[11]"]
set_property PACKAGE_PIN D25 [get_ports "C0_DDR4_ADDR[10]"]
set_property PACKAGE_PIN G21 [get_ports "C0_DDR4_ADDR[9]"]
set_property PACKAGE_PIN J20 [get_ports "C0_DDR4_ADDR[8]"]
set_property PACKAGE_PIN E20 [get_ports "C0_DDR4_ADDR[7]"]
set_property PACKAGE_PIN H20 [get_ports "C0_DDR4_ADDR[6]"]
set_property PACKAGE_PIN D20 [get_ports "C0_DDR4_ADDR[5]"]
set_property PACKAGE_PIN E21 [get_ports "C0_DDR4_ADDR[4]"]
set_property PACKAGE_PIN G20 [get_ports "C0_DDR4_ADDR[3]"]
set_property PACKAGE_PIN D21 [get_ports "C0_DDR4_ADDR[2]"]
set_property PACKAGE_PIN F22 [get_ports "C0_DDR4_ADDR[1]"]
set_property PACKAGE_PIN D22 [get_ports "C0_DDR4_ADDR[0]"]
# set_property PACKAGE_PIN M21 [get_ports "C0_DDR4_DM[8]"]
set_property PACKAGE_PIN C29 [get_ports "C0_DDR4_DM[7]"]
set_property PACKAGE_PIN F28 [get_ports "C0_DDR4_DM[6]"]
set_property PACKAGE_PIN J30 [get_ports "C0_DDR4_DM[5]"]
set_property PACKAGE_PIN M25 [get_ports "C0_DDR4_DM[4]"]
set_property PACKAGE_PIN F19 [get_ports "C0_DDR4_DM[3]"]
set_property PACKAGE_PIN M16 [get_ports "C0_DDR4_DM[2]"]
set_property PACKAGE_PIN J15 [get_ports "C0_DDR4_DM[1]"]
set_property PACKAGE_PIN C18 [get_ports "C0_DDR4_DM[0]"]
# set_property PACKAGE_PIN L21 [get_ports "C0_DDR4_DQS_T[8]"]
# set_property PACKAGE_PIN L22 [get_ports "C0_DDR4_DQS_C[8]"]
set_property PACKAGE_PIN B27 [get_ports "C0_DDR4_DQS_T[7]"]
set_property PACKAGE_PIN A27 [get_ports "C0_DDR4_DQS_C[7]"]
set_property PACKAGE_PIN E30 [get_ports "C0_DDR4_DQS_T[6]"]
set_property PACKAGE_PIN D30 [get_ports "C0_DDR4_DQS_C[6]"]
set_property PACKAGE_PIN G31 [get_ports "C0_DDR4_DQS_T[5]"]
set_property PACKAGE_PIN F31 [get_ports "C0_DDR4_DQS_C[5]"]
set_property PACKAGE_PIN J25 [get_ports "C0_DDR4_DQS_T[4]"]
set_property PACKAGE_PIN H25 [get_ports "C0_DDR4_DQS_C[4]"]
set_property PACKAGE_PIN E16 [get_ports "C0_DDR4_DQS_T[3]"]
set_property PACKAGE_PIN E15 [get_ports "C0_DDR4_DQS_C[3]"]
set_property PACKAGE_PIN L17 [get_ports "C0_DDR4_DQS_T[2]"]
set_property PACKAGE_PIN L16 [get_ports "C0_DDR4_DQS_C[2]"]
set_property PACKAGE_PIN G15 [get_ports "C0_DDR4_DQS_T[1]"]
set_property PACKAGE_PIN F14 [get_ports "C0_DDR4_DQS_C[1]"]
set_property PACKAGE_PIN B16 [get_ports "C0_DDR4_DQS_T[0]"]
set_property PACKAGE_PIN B15 [get_ports "C0_DDR4_DQS_C[0]"]
# set_property PACKAGE_PIN L23 [get_ports "C0_DDR4_DQ[71]"]
# set_property PACKAGE_PIN K23 [get_ports "C0_DDR4_DQ[70]"]
# set_property PACKAGE_PIN M19 [get_ports "C0_DDR4_DQ[69]"]
# set_property PACKAGE_PIN L24 [get_ports "C0_DDR4_DQ[68]"]
# set_property PACKAGE_PIN K21 [get_ports "C0_DDR4_DQ[67]"]
# set_property PACKAGE_PIN M20 [get_ports "C0_DDR4_DQ[66]"]
# set_property PACKAGE_PIN K20 [get_ports "C0_DDR4_DQ[65]"]
# set_property PACKAGE_PIN K24 [get_ports "C0_DDR4_DQ[64]"]
set_property PACKAGE_PIN A28 [get_ports "C0_DDR4_DQ[63]"]
set_property PACKAGE_PIN A31 [get_ports "C0_DDR4_DQ[62]"]
set_property PACKAGE_PIN A29 [get_ports "C0_DDR4_DQ[61]"]
set_property PACKAGE_PIN A26 [get_ports "C0_DDR4_DQ[60]"]
set_property PACKAGE_PIN C27 [get_ports "C0_DDR4_DQ[59]"]
set_property PACKAGE_PIN B31 [get_ports "C0_DDR4_DQ[58]"]
set_property PACKAGE_PIN B26 [get_ports "C0_DDR4_DQ[57]"]
set_property PACKAGE_PIN C28 [get_ports "C0_DDR4_DQ[56]"]
set_property PACKAGE_PIN D31 [get_ports "C0_DDR4_DQ[55]"]
set_property PACKAGE_PIN D27 [get_ports "C0_DDR4_DQ[54]"]
set_property PACKAGE_PIN E26 [get_ports "C0_DDR4_DQ[53]"]
set_property PACKAGE_PIN E28 [get_ports "C0_DDR4_DQ[52]"]
set_property PACKAGE_PIN E31 [get_ports "C0_DDR4_DQ[51]"]
set_property PACKAGE_PIN D28 [get_ports "C0_DDR4_DQ[50]"]
set_property PACKAGE_PIN E29 [get_ports "C0_DDR4_DQ[49]"]
set_property PACKAGE_PIN D26 [get_ports "C0_DDR4_DQ[48]"]
set_property PACKAGE_PIN H28 [get_ports "C0_DDR4_DQ[47]"]
set_property PACKAGE_PIN G29 [get_ports "C0_DDR4_DQ[46]"]
set_property PACKAGE_PIN H29 [get_ports "C0_DDR4_DQ[45]"]
set_property PACKAGE_PIN F27 [get_ports "C0_DDR4_DQ[44]"]
set_property PACKAGE_PIN J28 [get_ports "C0_DDR4_DQ[43]"]
set_property PACKAGE_PIN G30 [get_ports "C0_DDR4_DQ[42]"]
set_property PACKAGE_PIN H30 [get_ports "C0_DDR4_DQ[41]"]
set_property PACKAGE_PIN G27 [get_ports "C0_DDR4_DQ[40]"]
set_property PACKAGE_PIN J27 [get_ports "C0_DDR4_DQ[39]"]
set_property PACKAGE_PIN H27 [get_ports "C0_DDR4_DQ[38]"]
set_property PACKAGE_PIN J26 [get_ports "C0_DDR4_DQ[37]"]
set_property PACKAGE_PIN L26 [get_ports "C0_DDR4_DQ[36]"]
set_property PACKAGE_PIN L27 [get_ports "C0_DDR4_DQ[35]"]
set_property PACKAGE_PIN G26 [get_ports "C0_DDR4_DQ[34]"]
set_property PACKAGE_PIN G25 [get_ports "C0_DDR4_DQ[33]"]
set_property PACKAGE_PIN K26 [get_ports "C0_DDR4_DQ[32]"]
set_property PACKAGE_PIN F16 [get_ports "C0_DDR4_DQ[31]"]
set_property PACKAGE_PIN E19 [get_ports "C0_DDR4_DQ[30]"]
set_property PACKAGE_PIN D15 [get_ports "C0_DDR4_DQ[29]"]
set_property PACKAGE_PIN E18 [get_ports "C0_DDR4_DQ[28]"]
set_property PACKAGE_PIN D17 [get_ports "C0_DDR4_DQ[27]"]
set_property PACKAGE_PIN D18 [get_ports "C0_DDR4_DQ[26]"]
set_property PACKAGE_PIN D16 [get_ports "C0_DDR4_DQ[25]"]
set_property PACKAGE_PIN F17 [get_ports "C0_DDR4_DQ[24]"]
set_property PACKAGE_PIN K18 [get_ports "C0_DDR4_DQ[23]"]
set_property PACKAGE_PIN K19 [get_ports "C0_DDR4_DQ[22]"]
set_property PACKAGE_PIN K16 [get_ports "C0_DDR4_DQ[21]"]
set_property PACKAGE_PIN K15 [get_ports "C0_DDR4_DQ[20]"]
set_property PACKAGE_PIN L18 [get_ports "C0_DDR4_DQ[19]"]
set_property PACKAGE_PIN L19 [get_ports "C0_DDR4_DQ[18]"]
set_property PACKAGE_PIN J16 [get_ports "C0_DDR4_DQ[17]"]
set_property PACKAGE_PIN K14 [get_ports "C0_DDR4_DQ[16]"]
set_property PACKAGE_PIN H14 [get_ports "C0_DDR4_DQ[15]"]
set_property PACKAGE_PIN G19 [get_ports "C0_DDR4_DQ[14]"]
set_property PACKAGE_PIN G17 [get_ports "C0_DDR4_DQ[13]"]
set_property PACKAGE_PIN H17 [get_ports "C0_DDR4_DQ[12]"]
set_property PACKAGE_PIN H19 [get_ports "C0_DDR4_DQ[11]"]
set_property PACKAGE_PIN G14 [get_ports "C0_DDR4_DQ[10]"]
set_property PACKAGE_PIN G16 [get_ports "C0_DDR4_DQ[9]"]
set_property PACKAGE_PIN H18 [get_ports "C0_DDR4_DQ[8]"]
set_property PACKAGE_PIN A18 [get_ports "C0_DDR4_DQ[7]"]
set_property PACKAGE_PIN B19 [get_ports "C0_DDR4_DQ[6]"]
set_property PACKAGE_PIN C14 [get_ports "C0_DDR4_DQ[5]"]
set_property PACKAGE_PIN A16 [get_ports "C0_DDR4_DQ[4]"]
set_property PACKAGE_PIN A17 [get_ports "C0_DDR4_DQ[3]"]
set_property PACKAGE_PIN A19 [get_ports "C0_DDR4_DQ[2]"]
set_property PACKAGE_PIN C15 [get_ports "C0_DDR4_DQ[1]"]
set_property PACKAGE_PIN B17 [get_ports "C0_DDR4_DQ[0]"]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_ACT_B"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_CK_T[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_CK_C[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_CKE[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_ODT[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_CS_B[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_BA[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_BG[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_ADDR[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_DM[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_DQS_T[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_DQS_C[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C0_DDR4_DQ[*]"]

set_property IOSTANDARD  SSTL12_DCI       [get_ports "C0_DDR4_ACT_B"]
set_property IOSTANDARD  LVCMOS12         [get_ports "C0_DDR4_RESET_B"]
set_property DRIVE       8                [get_ports "C0_DDR4_RESET_B"]
set_property IOSTANDARD  DIFF_SSTL12_DCI  [get_ports "C0_DDR4_CK_T[*]"]
set_property IOSTANDARD  DIFF_SSTL12_DCI  [get_ports "C0_DDR4_CK_C[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C0_DDR4_CKE[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C0_DDR4_ODT[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C0_DDR4_CS_B[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C0_DDR4_BA[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C0_DDR4_BG[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C0_DDR4_ADDR[*]"]
set_property IOSTANDARD  POD12_DCI        [get_ports "C0_DDR4_DM[*]"]
set_property IOSTANDARD  DIFF_POD12_DCI   [get_ports "C0_DDR4_DQS_T[*]"]
set_property IOSTANDARD  DIFF_POD12_DCI   [get_ports "C0_DDR4_DQS_C[*]"]
set_property IOSTANDARD  POD12_DCI        [get_ports "C0_DDR4_DQ[*]"]

set_property SLEW FAST  [get_ports {C0_DDR4_ADDR[*] C0_DDR4_ACT_B C0_DDR4_BA[*] C0_DDR4_BG[*] C0_DDR4_CKE[*] C0_DDR4_CK_T[*] C0_DDR4_CK_C[*] C0_DDR4_ODT[*] C0_DDR4_DQ[*] C0_DDR4_DQS_T[*] C0_DDR4_DQS_C[*]}]
set_property IBUF_LOW_PWR FALSE  [get_ports {C0_DDR4_DQ[*] C0_DDR4_DQS_T[*] C0_DDR4_DQS_C[*]}]
set_property ODT RTT_40  [get_ports {C0_DDR4_DQ[*] C0_DDR4_DQS_T[*] C0_DDR4_DQS_C[*]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {C0_DDR4_DQ[*] C0_DDR4_DQS_T[*] C0_DDR4_DQS_C[*]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {C0_DDR4_DQ[*] C0_DDR4_DQS_T[*] C0_DDR4_DQS_C[*]}]
set_property SLEW FAST  [get_ports {C0_DDR4_CS_B[*]}]
set_property DATA_RATE SDR  [get_ports {C0_DDR4_CS_B[*]}]
set_property SLEW FAST  [get_ports {C0_DDR4_DM[*]}]
set_property IBUF_LOW_PWR FALSE  [get_ports {C0_DDR4_DM[*]}]
set_property ODT RTT_40  [get_ports {C0_DDR4_DM[*]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {C0_DDR4_DM[*]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {C0_DDR4_DM[*]}]
set_property DATA_RATE DDR [get_ports {C0_DDR4_DM[*]}]
set_property DATA_RATE SDR  [get_ports {C0_DDR4_ADDR[*] C0_DDR4_ACT_B C0_DDR4_BA[*] C0_DDR4_BG[*] C0_DDR4_CKE[*] C0_DDR4_ODT[*] }]
set_property DATA_RATE DDR  [get_ports {C0_DDR4_DQ[*] C0_DDR4_DQS_T[*] C0_DDR4_DQS_C[*] C0_DDR4_CK_T[*] C0_DDR4_CK_C[*]}]

## These below commands are used to create Interface ports for controller.
create_interface -quiet interface_ddr4_0
set_property interface interface_ddr4_0 [get_ports [list {C0_DDR4_ADDR[16]} {C0_DDR4_ADDR[15]} {C0_DDR4_ADDR[14]} {C0_DDR4_ADDR[13]} {C0_DDR4_ADDR[12]} {C0_DDR4_ADDR[11]} {C0_DDR4_ADDR[10]} {C0_DDR4_ADDR[9]} {C0_DDR4_ADDR[8]} {C0_DDR4_ADDR[7]} {C0_DDR4_ADDR[6]} {C0_DDR4_ADDR[5]} {C0_DDR4_ADDR[4]} {C0_DDR4_ADDR[3]} {C0_DDR4_ADDR[2]} {C0_DDR4_ADDR[1]} {C0_DDR4_ADDR[0]} {C0_DDR4_BA[1]} {C0_DDR4_BA[0]} {C0_DDR4_BG[1]} {C0_DDR4_BG[0]} {C0_DDR4_DQ[63]} {C0_DDR4_DQ[62]} {C0_DDR4_DQ[61]} {C0_DDR4_DQ[60]} {C0_DDR4_DQ[59]} {C0_DDR4_DQ[58]} {C0_DDR4_DQ[57]} {C0_DDR4_DQ[56]} {C0_DDR4_DQ[55]} {C0_DDR4_DQ[54]} {C0_DDR4_DQ[53]} {C0_DDR4_DQ[52]} {C0_DDR4_DQ[51]} {C0_DDR4_DQ[50]} {C0_DDR4_DQ[49]} {C0_DDR4_DQ[48]} {C0_DDR4_DQ[47]} {C0_DDR4_DQ[46]} {C0_DDR4_DQ[45]} {C0_DDR4_DQ[44]} {C0_DDR4_DQ[43]} {C0_DDR4_DQ[42]} {C0_DDR4_DQ[41]} {C0_DDR4_DQ[40]} {C0_DDR4_DQ[39]} {C0_DDR4_DQ[38]} {C0_DDR4_DQ[37]} {C0_DDR4_DQ[36]} {C0_DDR4_DQ[35]} {C0_DDR4_DQ[34]} {C0_DDR4_DQ[33]} {C0_DDR4_DQ[32]} {C0_DDR4_DQ[31]} {C0_DDR4_DQ[30]} {C0_DDR4_DQ[29]} {C0_DDR4_DQ[28]} {C0_DDR4_DQ[27]} {C0_DDR4_DQ[26]} {C0_DDR4_DQ[25]} {C0_DDR4_DQ[24]} {C0_DDR4_DQ[23]} {C0_DDR4_DQ[22]} {C0_DDR4_DQ[21]} {C0_DDR4_DQ[20]} {C0_DDR4_DQ[19]} {C0_DDR4_DQ[18]} {C0_DDR4_DQ[17]} {C0_DDR4_DQ[16]} {C0_DDR4_DQ[15]} {C0_DDR4_DQ[14]} {C0_DDR4_DQ[13]} {C0_DDR4_DQ[12]} {C0_DDR4_DQ[11]} {C0_DDR4_DQ[10]} {C0_DDR4_DQ[9]} {C0_DDR4_DQ[8]} {C0_DDR4_DQ[7]} {C0_DDR4_DQ[6]} {C0_DDR4_DQ[5]} {C0_DDR4_DQ[4]} {C0_DDR4_DQ[3]} {C0_DDR4_DQ[2]} {C0_DDR4_DQ[1]} {C0_DDR4_DQ[0]} {C0_DDR4_DQS_C[7]} {C0_DDR4_DQS_T[7]} {C0_DDR4_DQS_C[6]} {C0_DDR4_DQS_T[6]} {C0_DDR4_DQS_C[5]} {C0_DDR4_DQS_T[5]} {C0_DDR4_DQS_C[4]} {C0_DDR4_DQS_T[4]} {C0_DDR4_DQS_C[3]} {C0_DDR4_DQS_T[3]} {C0_DDR4_DQS_C[2]} {C0_DDR4_DQS_T[2]} {C0_DDR4_DQS_C[1]} {C0_DDR4_DQS_T[1]} {C0_DDR4_DQS_C[0]} {C0_DDR4_DQS_T[0]} {C0_DDR4_DM[7]} {C0_DDR4_DM[6]} {C0_DDR4_DM[5]} {C0_DDR4_DM[4]} {C0_DDR4_DM[3]} {C0_DDR4_DM[2]} {C0_DDR4_DM[1]} {C0_DDR4_DM[0]} {C0_DDR4_CK_T[1]} {C0_DDR4_CK_C[1]} {C0_DDR4_CK_T[0]} {C0_DDR4_CK_C[0]} {C0_DDR4_CKE[1]} {C0_DDR4_CKE[0]} {C0_DDR4_CS_B[1]} {C0_DDR4_CS_B[0]} {C0_DDR4_ODT[1]} {C0_DDR4_ODT[0]} C0_DDR4_RESET_B C0_DDR4_ACT_B]]

##############################################################################
# DDR4 B
set_property PACKAGE_PIN AN13 [get_ports "C1_DDR4_ACT_B"]
set_property PACKAGE_PIN AM13 [get_ports "C1_DDR4_RESET_B"]
set_property PACKAGE_PIN AW14 [get_ports "C1_DDR4_CK_T[1]"]
set_property PACKAGE_PIN AW13 [get_ports "C1_DDR4_CK_C[1]"]
set_property PACKAGE_PIN AW11 [get_ports "C1_DDR4_CK_T[0]"]
set_property PACKAGE_PIN AW10 [get_ports "C1_DDR4_CK_C[0]"]
set_property PACKAGE_PIN AW15 [get_ports "C1_DDR4_CKE[1]"]
set_property PACKAGE_PIN AW16 [get_ports "C1_DDR4_CKE[0]"]
set_property PACKAGE_PIN AN12 [get_ports "C1_DDR4_ODT[1]"]
set_property PACKAGE_PIN AP14 [get_ports "C1_DDR4_ODT[0]"]
# set_property PACKAGE_PIN AP15 [get_ports "C1_DDR4_PARITY"]
# set_property PACKAGE_PIN AM14 [get_ports "C1_DDR4_EVENT_B"]
# set_property PACKAGE_PIN AP16 [get_ports "C1_DDR4_ALERT_B"]
# set_property PACKAGE_PIN AM12 [get_ports "C1_DDR4_CS_B[3]"]
# set_property PACKAGE_PIN AR13 [get_ports "C1_DDR4_CS_B[2]"]
set_property PACKAGE_PIN AP13 [get_ports "C1_DDR4_CS_B[1]"]
set_property PACKAGE_PIN AR12 [get_ports "C1_DDR4_CS_B[0]"]
set_property PACKAGE_PIN AU12 [get_ports "C1_DDR4_BA[1]"]
set_property PACKAGE_PIN AT14 [get_ports "C1_DDR4_BA[0]"]
set_property PACKAGE_PIN AT16 [get_ports "C1_DDR4_BG[1]"]
set_property PACKAGE_PIN AR14 [get_ports "C1_DDR4_BG[0]"]
set_property PACKAGE_PIN AR16 [get_ports "C1_DDR4_ADDR[16]"]
set_property PACKAGE_PIN AP11 [get_ports "C1_DDR4_ADDR[15]"]
set_property PACKAGE_PIN AR11 [get_ports "C1_DDR4_ADDR[14]"]
set_property PACKAGE_PIN AP10 [get_ports "C1_DDR4_ADDR[13]"]
set_property PACKAGE_PIN AV16 [get_ports "C1_DDR4_ADDR[12]"]
set_property PACKAGE_PIN AT15 [get_ports "C1_DDR4_ADDR[11]"]
set_property PACKAGE_PIN AT11 [get_ports "C1_DDR4_ADDR[10]"]
set_property PACKAGE_PIN AV15 [get_ports "C1_DDR4_ADDR[9]"]
set_property PACKAGE_PIN AU14 [get_ports "C1_DDR4_ADDR[8]"]
set_property PACKAGE_PIN AU13 [get_ports "C1_DDR4_ADDR[7]"]
set_property PACKAGE_PIN AV13 [get_ports "C1_DDR4_ADDR[6]"]
set_property PACKAGE_PIN AU15 [get_ports "C1_DDR4_ADDR[5]"]
set_property PACKAGE_PIN AV12 [get_ports "C1_DDR4_ADDR[4]"]
set_property PACKAGE_PIN AV11 [get_ports "C1_DDR4_ADDR[3]"]
set_property PACKAGE_PIN AT12 [get_ports "C1_DDR4_ADDR[2]"]
set_property PACKAGE_PIN AV10 [get_ports "C1_DDR4_ADDR[1]"]
set_property PACKAGE_PIN AU10 [get_ports "C1_DDR4_ADDR[0]"]
# set_property PACKAGE_PIN AL15 [get_ports "C1_DDR4_DM[8]"]
set_property PACKAGE_PIN AP19 [get_ports "C1_DDR4_DM[7]"]
set_property PACKAGE_PIN AH21 [get_ports "C1_DDR4_DM[6]"]
set_property PACKAGE_PIN AR22 [get_ports "C1_DDR4_DM[5]"]
set_property PACKAGE_PIN AU22 [get_ports "C1_DDR4_DM[4]"]
set_property PACKAGE_PIN AW23 [get_ports "C1_DDR4_DM[3]"]
set_property PACKAGE_PIN AR23 [get_ports "C1_DDR4_DM[2]"]
set_property PACKAGE_PIN AM23 [get_ports "C1_DDR4_DM[1]"]
set_property PACKAGE_PIN AL25 [get_ports "C1_DDR4_DM[0]"]
# set_property PACKAGE_PIN AK17 [get_ports "C1_DDR4_DQS_T[8]"]
# set_property PACKAGE_PIN AL17 [get_ports "C1_DDR4_DQS_C[8]"]
set_property PACKAGE_PIN AT17 [get_ports "C1_DDR4_DQS_T[7]"]
set_property PACKAGE_PIN AU17 [get_ports "C1_DDR4_DQS_C[7]"]
set_property PACKAGE_PIN AK19 [get_ports "C1_DDR4_DQS_T[6]"]
set_property PACKAGE_PIN AK18 [get_ports "C1_DDR4_DQS_C[6]"]
set_property PACKAGE_PIN AK21 [get_ports "C1_DDR4_DQS_T[5]"]
set_property PACKAGE_PIN AL21 [get_ports "C1_DDR4_DQS_C[5]"]
set_property PACKAGE_PIN AW20 [get_ports "C1_DDR4_DQS_T[4]"]
set_property PACKAGE_PIN AW19 [get_ports "C1_DDR4_DQS_C[4]"]
set_property PACKAGE_PIN AU25 [get_ports "C1_DDR4_DQS_T[3]"]
set_property PACKAGE_PIN AV25 [get_ports "C1_DDR4_DQS_C[3]"]
set_property PACKAGE_PIN AR26 [get_ports "C1_DDR4_DQS_T[2]"]
set_property PACKAGE_PIN AR27 [get_ports "C1_DDR4_DQS_C[2]"]
set_property PACKAGE_PIN AH25 [get_ports "C1_DDR4_DQS_T[1]"]
set_property PACKAGE_PIN AJ25 [get_ports "C1_DDR4_DQS_C[1]"]
set_property PACKAGE_PIN AH26 [get_ports "C1_DDR4_DQS_T[0]"]
set_property PACKAGE_PIN AH27 [get_ports "C1_DDR4_DQS_C[0]"]
# set_property PACKAGE_PIN AL16 [get_ports "C1_DDR4_DQ[71]"]
# set_property PACKAGE_PIN AJ15 [get_ports "C1_DDR4_DQ[70]"]
# set_property PACKAGE_PIN AK16 [get_ports "C1_DDR4_DQ[69]"]
# set_property PACKAGE_PIN AJ14 [get_ports "C1_DDR4_DQ[68]"]
# set_property PACKAGE_PIN AN15 [get_ports "C1_DDR4_DQ[67]"]
# set_property PACKAGE_PIN AM15 [get_ports "C1_DDR4_DQ[66]"]
# set_property PACKAGE_PIN AJ16 [get_ports "C1_DDR4_DQ[65]"]
# set_property PACKAGE_PIN AK14 [get_ports "C1_DDR4_DQ[64]"]
set_property PACKAGE_PIN AU19 [get_ports "C1_DDR4_DQ[63]"]
set_property PACKAGE_PIN AT19 [get_ports "C1_DDR4_DQ[62]"]
set_property PACKAGE_PIN AR17 [get_ports "C1_DDR4_DQ[61]"]
set_property PACKAGE_PIN AT20 [get_ports "C1_DDR4_DQ[60]"]
set_property PACKAGE_PIN AU18 [get_ports "C1_DDR4_DQ[59]"]
set_property PACKAGE_PIN AN18 [get_ports "C1_DDR4_DQ[58]"]
set_property PACKAGE_PIN AR18 [get_ports "C1_DDR4_DQ[57]"]
set_property PACKAGE_PIN AP18 [get_ports "C1_DDR4_DQ[56]"]
set_property PACKAGE_PIN AJ18 [get_ports "C1_DDR4_DQ[55]"]
set_property PACKAGE_PIN AJ20 [get_ports "C1_DDR4_DQ[54]"]
set_property PACKAGE_PIN AM19 [get_ports "C1_DDR4_DQ[53]"]
set_property PACKAGE_PIN AM17 [get_ports "C1_DDR4_DQ[52]"]
set_property PACKAGE_PIN AJ19 [get_ports "C1_DDR4_DQ[51]"]
set_property PACKAGE_PIN AH18 [get_ports "C1_DDR4_DQ[50]"]
set_property PACKAGE_PIN AL19 [get_ports "C1_DDR4_DQ[49]"]
set_property PACKAGE_PIN AM18 [get_ports "C1_DDR4_DQ[48]"]
set_property PACKAGE_PIN AP21 [get_ports "C1_DDR4_DQ[47]"]
set_property PACKAGE_PIN AL20 [get_ports "C1_DDR4_DQ[46]"]
set_property PACKAGE_PIN AM22 [get_ports "C1_DDR4_DQ[45]"]
set_property PACKAGE_PIN AP20 [get_ports "C1_DDR4_DQ[44]"]
set_property PACKAGE_PIN AM20 [get_ports "C1_DDR4_DQ[43]"]
set_property PACKAGE_PIN AL22 [get_ports "C1_DDR4_DQ[42]"]
set_property PACKAGE_PIN AN21 [get_ports "C1_DDR4_DQ[41]"]
set_property PACKAGE_PIN AN20 [get_ports "C1_DDR4_DQ[40]"]
set_property PACKAGE_PIN AV20 [get_ports "C1_DDR4_DQ[39]"]
set_property PACKAGE_PIN AT21 [get_ports "C1_DDR4_DQ[38]"]
set_property PACKAGE_PIN AV18 [get_ports "C1_DDR4_DQ[37]"]
set_property PACKAGE_PIN AW21 [get_ports "C1_DDR4_DQ[36]"]
set_property PACKAGE_PIN AU20 [get_ports "C1_DDR4_DQ[35]"]
set_property PACKAGE_PIN AT22 [get_ports "C1_DDR4_DQ[34]"]
set_property PACKAGE_PIN AW18 [get_ports "C1_DDR4_DQ[33]"]
set_property PACKAGE_PIN AV21 [get_ports "C1_DDR4_DQ[32]"]
set_property PACKAGE_PIN AV27 [get_ports "C1_DDR4_DQ[31]"]
set_property PACKAGE_PIN AV23 [get_ports "C1_DDR4_DQ[30]"]
set_property PACKAGE_PIN AW25 [get_ports "C1_DDR4_DQ[29]"]
set_property PACKAGE_PIN AU24 [get_ports "C1_DDR4_DQ[28]"]
set_property PACKAGE_PIN AW26 [get_ports "C1_DDR4_DQ[27]"]
set_property PACKAGE_PIN AU23 [get_ports "C1_DDR4_DQ[26]"]
set_property PACKAGE_PIN AT24 [get_ports "C1_DDR4_DQ[25]"]
set_property PACKAGE_PIN AV26 [get_ports "C1_DDR4_DQ[24]"]
set_property PACKAGE_PIN AT26 [get_ports "C1_DDR4_DQ[23]"]
set_property PACKAGE_PIN AP23 [get_ports "C1_DDR4_DQ[22]"]
set_property PACKAGE_PIN AP26 [get_ports "C1_DDR4_DQ[21]"]
set_property PACKAGE_PIN AN25 [get_ports "C1_DDR4_DQ[20]"]
set_property PACKAGE_PIN AT25 [get_ports "C1_DDR4_DQ[19]"]
set_property PACKAGE_PIN AN23 [get_ports "C1_DDR4_DQ[18]"]
set_property PACKAGE_PIN AP25 [get_ports "C1_DDR4_DQ[17]"]
set_property PACKAGE_PIN AP24 [get_ports "C1_DDR4_DQ[16]"]
set_property PACKAGE_PIN AK23 [get_ports "C1_DDR4_DQ[15]"]
set_property PACKAGE_PIN AK24 [get_ports "C1_DDR4_DQ[14]"]
set_property PACKAGE_PIN AL24 [get_ports "C1_DDR4_DQ[13]"]
set_property PACKAGE_PIN AH23 [get_ports "C1_DDR4_DQ[12]"]
set_property PACKAGE_PIN AJ23 [get_ports "C1_DDR4_DQ[11]"]
set_property PACKAGE_PIN AK22 [get_ports "C1_DDR4_DQ[10]"]
set_property PACKAGE_PIN AM25 [get_ports "C1_DDR4_DQ[9]"]
set_property PACKAGE_PIN AJ24 [get_ports "C1_DDR4_DQ[8]"]
set_property PACKAGE_PIN AN27 [get_ports "C1_DDR4_DQ[7]"]
set_property PACKAGE_PIN AK26 [get_ports "C1_DDR4_DQ[6]"]
set_property PACKAGE_PIN AK27 [get_ports "C1_DDR4_DQ[5]"]
set_property PACKAGE_PIN AJ28 [get_ports "C1_DDR4_DQ[4]"]
set_property PACKAGE_PIN AN26 [get_ports "C1_DDR4_DQ[3]"]
set_property PACKAGE_PIN AJ26 [get_ports "C1_DDR4_DQ[2]"]
set_property PACKAGE_PIN AL27 [get_ports "C1_DDR4_DQ[1]"]
set_property PACKAGE_PIN AK28 [get_ports "C1_DDR4_DQ[0]"]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_ACT_B"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_CK_T[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_CK_C[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_CKE[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_ODT[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_CS_B[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_BA[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_BG[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_ADDR[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_DM[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_DQS_T[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_DQS_C[*]"]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "C1_DDR4_DQ[*]"]

set_property IOSTANDARD  SSTL12_DCI       [get_ports "C1_DDR4_ACT_B"]
set_property IOSTANDARD  LVCMOS12         [get_ports "C1_DDR4_RESET_B"]
set_property DRIVE       8                [get_ports "C1_DDR4_RESET_B"]
set_property IOSTANDARD  DIFF_SSTL12_DCI  [get_ports "C1_DDR4_CK_T[*]"]
set_property IOSTANDARD  DIFF_SSTL12_DCI  [get_ports "C1_DDR4_CK_C[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C1_DDR4_CKE[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C1_DDR4_ODT[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C1_DDR4_CS_B[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C1_DDR4_BA[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C1_DDR4_BG[*]"]
set_property IOSTANDARD  SSTL12_DCI       [get_ports "C1_DDR4_ADDR[*]"]
set_property IOSTANDARD  POD12_DCI        [get_ports "C1_DDR4_DM[*]"]
set_property IOSTANDARD  DIFF_POD12_DCI   [get_ports "C1_DDR4_DQS_T[*]"]
set_property IOSTANDARD  DIFF_POD12_DCI   [get_ports "C1_DDR4_DQS_C[*]"]
set_property IOSTANDARD  POD12_DCI        [get_ports "C1_DDR4_DQ[*]"]

set_property SLEW FAST  [get_ports {C1_DDR4_ADDR[*] C1_DDR4_ACT_B C1_DDR4_BA[*] C1_DDR4_BG[*] C1_DDR4_CKE[*] C1_DDR4_CK_T[*] C1_DDR4_CK_C[*] C1_DDR4_ODT[*] C1_DDR4_DQ[*] C1_DDR4_DQS_T[*] C1_DDR4_DQS_C[*]}]
set_property IBUF_LOW_PWR FALSE  [get_ports {C1_DDR4_DQ[*] C1_DDR4_DQS_T[*] C1_DDR4_DQS_C[*]}]
set_property ODT RTT_40  [get_ports {C1_DDR4_DQ[*] C1_DDR4_DQS_T[*] C1_DDR4_DQS_C[*]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {C1_DDR4_DQ[*] C1_DDR4_DQS_T[*] C1_DDR4_DQS_C[*]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {C1_DDR4_DQ[*] C1_DDR4_DQS_T[*] C1_DDR4_DQS_C[*]}]
set_property SLEW FAST  [get_ports {C1_DDR4_CS_B[*]}]
set_property DATA_RATE SDR  [get_ports {C1_DDR4_CS_B[*]}]
set_property SLEW FAST  [get_ports {C1_DDR4_DM[*]}]
set_property IBUF_LOW_PWR FALSE  [get_ports {C1_DDR4_DM[*]}]
set_property ODT RTT_40  [get_ports {C1_DDR4_DM[*]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {C1_DDR4_DM[*]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {C1_DDR4_DM[*]}]
set_property DATA_RATE DDR [get_ports {C1_DDR4_DM[*]}]
set_property DATA_RATE SDR  [get_ports {C1_DDR4_ADDR[*] C1_DDR4_ACT_B C1_DDR4_BA[*] C1_DDR4_BG[*] C1_DDR4_CKE[*] C1_DDR4_ODT[*] }]
set_property DATA_RATE DDR  [get_ports {C1_DDR4_DQ[*] C1_DDR4_DQS_T[*] C1_DDR4_DQS_C[*] C1_DDR4_CK_T[*] C1_DDR4_CK_C[*]}]

## These below commands are used to create Interface ports for controller.
create_interface -quiet interface_ddr4_1
set_property interface interface_ddr4_1 [get_ports [list {C1_DDR4_ADDR[16]} {C1_DDR4_ADDR[15]} {C1_DDR4_ADDR[14]} {C1_DDR4_ADDR[13]} {C1_DDR4_ADDR[12]} {C1_DDR4_ADDR[11]} {C1_DDR4_ADDR[10]} {C1_DDR4_ADDR[9]} {C1_DDR4_ADDR[8]} {C1_DDR4_ADDR[7]} {C1_DDR4_ADDR[6]} {C1_DDR4_ADDR[5]} {C1_DDR4_ADDR[4]} {C1_DDR4_ADDR[3]} {C1_DDR4_ADDR[2]} {C1_DDR4_ADDR[1]} {C1_DDR4_ADDR[0]} {C1_DDR4_BA[1]} {C1_DDR4_BA[0]} {C1_DDR4_BG[1]} {C1_DDR4_BG[0]} {C1_DDR4_DQ[63]} {C1_DDR4_DQ[62]} {C1_DDR4_DQ[61]} {C1_DDR4_DQ[60]} {C1_DDR4_DQ[59]} {C1_DDR4_DQ[58]} {C1_DDR4_DQ[57]} {C1_DDR4_DQ[56]} {C1_DDR4_DQ[55]} {C1_DDR4_DQ[54]} {C1_DDR4_DQ[53]} {C1_DDR4_DQ[52]} {C1_DDR4_DQ[51]} {C1_DDR4_DQ[50]} {C1_DDR4_DQ[49]} {C1_DDR4_DQ[48]} {C1_DDR4_DQ[47]} {C1_DDR4_DQ[46]} {C1_DDR4_DQ[45]} {C1_DDR4_DQ[44]} {C1_DDR4_DQ[43]} {C1_DDR4_DQ[42]} {C1_DDR4_DQ[41]} {C1_DDR4_DQ[40]} {C1_DDR4_DQ[39]} {C1_DDR4_DQ[38]} {C1_DDR4_DQ[37]} {C1_DDR4_DQ[36]} {C1_DDR4_DQ[35]} {C1_DDR4_DQ[34]} {C1_DDR4_DQ[33]} {C1_DDR4_DQ[32]} {C1_DDR4_DQ[31]} {C1_DDR4_DQ[30]} {C1_DDR4_DQ[29]} {C1_DDR4_DQ[28]} {C1_DDR4_DQ[27]} {C1_DDR4_DQ[26]} {C1_DDR4_DQ[25]} {C1_DDR4_DQ[24]} {C1_DDR4_DQ[23]} {C1_DDR4_DQ[22]} {C1_DDR4_DQ[21]} {C1_DDR4_DQ[20]} {C1_DDR4_DQ[19]} {C1_DDR4_DQ[18]} {C1_DDR4_DQ[17]} {C1_DDR4_DQ[16]} {C1_DDR4_DQ[15]} {C1_DDR4_DQ[14]} {C1_DDR4_DQ[13]} {C1_DDR4_DQ[12]} {C1_DDR4_DQ[11]} {C1_DDR4_DQ[10]} {C1_DDR4_DQ[9]} {C1_DDR4_DQ[8]} {C1_DDR4_DQ[7]} {C1_DDR4_DQ[6]} {C1_DDR4_DQ[5]} {C1_DDR4_DQ[4]} {C1_DDR4_DQ[3]} {C1_DDR4_DQ[2]} {C1_DDR4_DQ[1]} {C1_DDR4_DQ[0]} {C1_DDR4_DQS_C[7]} {C1_DDR4_DQS_T[7]} {C1_DDR4_DQS_C[6]} {C1_DDR4_DQS_T[6]} {C1_DDR4_DQS_C[5]} {C1_DDR4_DQS_T[5]} {C1_DDR4_DQS_C[4]} {C1_DDR4_DQS_T[4]} {C1_DDR4_DQS_C[3]} {C1_DDR4_DQS_T[3]} {C1_DDR4_DQS_C[2]} {C1_DDR4_DQS_T[2]} {C1_DDR4_DQS_C[1]} {C1_DDR4_DQS_T[1]} {C1_DDR4_DQS_C[0]} {C1_DDR4_DQS_T[0]} {C1_DDR4_DM[7]} {C1_DDR4_DM[6]} {C1_DDR4_DM[5]} {C1_DDR4_DM[4]} {C1_DDR4_DM[3]} {C1_DDR4_DM[2]} {C1_DDR4_DM[1]} {C1_DDR4_DM[0]} {C1_DDR4_CK_T[1]} {C1_DDR4_CK_C[1]} {C1_DDR4_CK_T[0]} {C1_DDR4_CK_C[0]} {C1_DDR4_CKE[1]} {C1_DDR4_CKE[0]} {C1_DDR4_CS_B[1]} {C1_DDR4_CS_B[0]} {C1_DDR4_ODT[1]} {C1_DDR4_ODT[0]} C1_DDR4_RESET_B C1_DDR4_ACT_B]]

##############################################################################
# FMC0
set_property PACKAGE_PIN D1 [get_ports "FMC0_PRSNT_B"]
set_property IOSTANDARD LVCMOS33 [get_ports "FMC0_PRSNT_B"]
# Drive high to enable output CLK_BIDIR2 and CLK_BIDIR3 as C2M
set_property PACKAGE_PIN D2 [get_ports "FMC0_CLK_DIR"]
set_property IOSTANDARD LVCMOS33 [get_ports "FMC0_CLK_DIR"]

# FMC CLK_M2C0 and CLK_BIDIR2 to clk mux; CLK_M2C1 and CLK_BIDIR3 to FPGA
set_property PACKAGE_PIN AT32 [get_ports "FMC0_CLK_M2C_N1"]
set_property PACKAGE_PIN AR32 [get_ports "FMC0_CLK_M2C_P1"]
set_property PACKAGE_PIN AU35 [get_ports "FMC0_CLK_M2C_N3"]
set_property PACKAGE_PIN AU34 [get_ports "FMC0_CLK_M2C_P3"]
set_property PACKAGE_PIN AU30 [get_ports "FMC0_CLK_C2M_N3"]
set_property PACKAGE_PIN AT30 [get_ports "FMC0_CLK_C2M_P3"]
# HP bank
set_property PACKAGE_PIN AT34 [get_ports "FMC0_LA_N0"]
set_property PACKAGE_PIN AR34 [get_ports "FMC0_LA_P0"]
set_property PACKAGE_PIN AV36 [get_ports "FMC0_LA_N1"]
set_property PACKAGE_PIN AV35 [get_ports "FMC0_LA_P1"]
set_property PACKAGE_PIN AW30 [get_ports "FMC0_LA_N2"]
set_property PACKAGE_PIN AV30 [get_ports "FMC0_LA_P2"]
set_property PACKAGE_PIN AW31 [get_ports "FMC0_LA_N3"]
set_property PACKAGE_PIN AV31 [get_ports "FMC0_LA_P3"]
set_property PACKAGE_PIN AV33 [get_ports "FMC0_LA_N4"]
set_property PACKAGE_PIN AV32 [get_ports "FMC0_LA_P4"]
set_property PACKAGE_PIN AT36 [get_ports "FMC0_LA_N5"]
set_property PACKAGE_PIN AT35 [get_ports "FMC0_LA_P5"]
set_property PACKAGE_PIN AV37 [get_ports "FMC0_LA_N6"]
set_property PACKAGE_PIN AU37 [get_ports "FMC0_LA_P6"]
set_property PACKAGE_PIN AV38 [get_ports "FMC0_LA_N7"]
set_property PACKAGE_PIN AU38 [get_ports "FMC0_LA_P7"]
set_property PACKAGE_PIN AW35 [get_ports "FMC0_LA_N8"]
set_property PACKAGE_PIN AW34 [get_ports "FMC0_LA_P8"]
set_property PACKAGE_PIN AU39 [get_ports "FMC0_LA_N9"]
set_property PACKAGE_PIN AT39 [get_ports "FMC0_LA_P9"]
set_property PACKAGE_PIN AT37 [get_ports "FMC0_LA_N10"]
set_property PACKAGE_PIN AR37 [get_ports "FMC0_LA_P10"]
set_property PACKAGE_PIN AR39 [get_ports "FMC0_LA_N11"]
set_property PACKAGE_PIN AR38 [get_ports "FMC0_LA_P11"]
set_property PACKAGE_PIN AT31 [get_ports "FMC0_LA_N12"]
set_property PACKAGE_PIN AR31 [get_ports "FMC0_LA_P12"]
set_property PACKAGE_PIN AP39 [get_ports "FMC0_LA_N13"]
set_property PACKAGE_PIN AP38 [get_ports "FMC0_LA_P13"]
set_property PACKAGE_PIN AR36 [get_ports "FMC0_LA_N14"]
set_property PACKAGE_PIN AP36 [get_ports "FMC0_LA_P14"]
set_property PACKAGE_PIN AP35 [get_ports "FMC0_LA_N15"]
set_property PACKAGE_PIN AP34 [get_ports "FMC0_LA_P15"]
set_property PACKAGE_PIN AR33 [get_ports "FMC0_LA_N16"]
set_property PACKAGE_PIN AP33 [get_ports "FMC0_LA_P16"]
# 1.0V: POD10 and DIFF_POD10
# 1.2V: LVCMOS12 and DIFF_HSUL_12
# 1.5V: LVCMOS15 and DIFF_SSTL15
# 1.8V: LVCMOS18 and LVDS
set_property IOSTANDARD LVDS [get_ports "FMC0_CLK_M2C_N1"]
set_property IOSTANDARD LVDS [get_ports "FMC0_CLK_M2C_P1"]
set_property IOSTANDARD LVDS [get_ports "FMC0_CLK_M2C_N3"]
set_property IOSTANDARD LVDS [get_ports "FMC0_CLK_M2C_P3"]
set_property IOSTANDARD LVDS [get_ports "FMC0_CLK_C2M_N3"]
set_property IOSTANDARD LVDS [get_ports "FMC0_CLK_C2M_P3"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N0"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P0"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N1"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P1"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N2"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P2"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N3"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P3"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N4"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P4"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N5"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P5"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N6"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P6"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N7"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P7"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N8"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P8"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N9"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P9"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N10"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P10"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N11"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P11"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N12"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P12"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N13"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P13"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N14"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P14"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N15"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P15"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_N16"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC0_LA_P16"]

# HB for monitoring
set_property PACKAGE_PIN A3 [get_ports "FMC0_HB_N0"]
set_property PACKAGE_PIN A4 [get_ports "FMC0_HB_P0"]
set_property PACKAGE_PIN F2 [get_ports "FMC0_HB_N1"]
set_property PACKAGE_PIN F3 [get_ports "FMC0_HB_P1"]
set_property PACKAGE_PIN B2 [get_ports "FMC0_HB_N2"]
set_property PACKAGE_PIN C2 [get_ports "FMC0_HB_P2"]
set_property PACKAGE_PIN E1 [get_ports "FMC0_HB_N3"]
set_property PACKAGE_PIN F1 [get_ports "FMC0_HB_P3"]
set_property PACKAGE_PIN E4 [get_ports "FMC0_HB_N4"]
set_property PACKAGE_PIN E5 [get_ports "FMC0_HB_P4"]
set_property PACKAGE_PIN E3 [get_ports "FMC0_HB_N5"]
set_property PACKAGE_PIN F4 [get_ports "FMC0_HB_P5"]
set_property PACKAGE_PIN A6 [get_ports "FMC0_HB_N6"]
set_property PACKAGE_PIN B6 [get_ports "FMC0_HB_P6"]
set_property PACKAGE_PIN B4 [get_ports "FMC0_HB_N7"]
set_property PACKAGE_PIN B5 [get_ports "FMC0_HB_P7"]
set_property IOSTANDARD  LVCMOS33 [get_ports "FMC0_HB_P*"]
set_property IOSTANDARD  LVCMOS33 [get_ports "FMC0_HB_N*"]

# GTY for FMC0
# BANK_128
# set_property PACKAGE_PIN AD36 [get_ports "FMC0_DP_M2C_P3"]
# set_property PACKAGE_PIN AD37 [get_ports "FMC0_DP_M2C_N3"]
# set_property PACKAGE_PIN AC38 [get_ports "FMC0_DP_M2C_P2"]
# set_property PACKAGE_PIN AC39 [get_ports "FMC0_DP_M2C_N2"]
# set_property PACKAGE_PIN AB36 [get_ports "FMC0_DP_M2C_P1"]
# set_property PACKAGE_PIN AB37 [get_ports "FMC0_DP_M2C_N1"]
# set_property PACKAGE_PIN AA38 [get_ports "FMC0_DP_M2C_P0"]
# set_property PACKAGE_PIN AA39 [get_ports "FMC0_DP_M2C_N0"]
# set_property PACKAGE_PIN AB31 [get_ports "FMC0_DP_C2M_P3"]
# set_property PACKAGE_PIN AB32 [get_ports "FMC0_DP_C2M_N3"]
# set_property PACKAGE_PIN AA33 [get_ports "FMC0_DP_C2M_P2"]
# set_property PACKAGE_PIN AA34 [get_ports "FMC0_DP_C2M_N2"]
# set_property PACKAGE_PIN Y32  [get_ports "FMC0_DP_C2M_N1"]
# set_property PACKAGE_PIN Y31  [get_ports "FMC0_DP_C2M_P1"]
# set_property PACKAGE_PIN W34  [get_ports "FMC0_DP_C2M_N0"]
# set_property PACKAGE_PIN W33  [get_ports "FMC0_DP_C2M_P0"]
# set_property PACKAGE_PIN AB27 [get_ports "MGTCLK128_P0"]
# set_property PACKAGE_PIN AB28 [get_ports "MGTCLK128_N0"]
# set_property PACKAGE_PIN AA29 [get_ports "MGTCLK128_P1"]
# set_property PACKAGE_PIN AA30 [get_ports "MGTCLK128_N1"]

# BANK_127
# set_property PACKAGE_PIN AH36 [get_ports "FMC0_DP_M2C_P7"]
# set_property PACKAGE_PIN AH37 [get_ports "FMC0_DP_M2C_N7"]
# set_property PACKAGE_PIN AG38 [get_ports "FMC0_DP_M2C_P6"]
# set_property PACKAGE_PIN AG39 [get_ports "FMC0_DP_M2C_N6"]
# set_property PACKAGE_PIN AF36 [get_ports "FMC0_DP_M2C_P5"]
# set_property PACKAGE_PIN AF37 [get_ports "FMC0_DP_M2C_N5"]
# set_property PACKAGE_PIN AE38 [get_ports "FMC0_DP_M2C_P4"]
# set_property PACKAGE_PIN AE39 [get_ports "FMC0_DP_M2C_N4"]
# set_property PACKAGE_PIN AF31 [get_ports "FMC0_DP_C2M_P7"]
# set_property PACKAGE_PIN AF32 [get_ports "FMC0_DP_C2M_N7"]
# set_property PACKAGE_PIN AE33 [get_ports "FMC0_DP_C2M_P6"]
# set_property PACKAGE_PIN AE34 [get_ports "FMC0_DP_C2M_N6"]
# set_property PACKAGE_PIN AD31 [get_ports "FMC0_DP_C2M_P5"]
# set_property PACKAGE_PIN AD32 [get_ports "FMC0_DP_C2M_N5"]
# set_property PACKAGE_PIN AC33 [get_ports "FMC0_DP_C2M_P4"]
# set_property PACKAGE_PIN AC34 [get_ports "FMC0_DP_C2M_N4"]
# set_property PACKAGE_PIN AE29 [get_ports "MGTCLK127_P0"]
# set_property PACKAGE_PIN AE30 [get_ports "MGTCLK127_N0"]
# set_property PACKAGE_PIN AC29 [get_ports "MGTCLK127_P1"]
# set_property PACKAGE_PIN AC30 [get_ports "MGTCLK127_N1"]

##############################################################################
# FMC1
set_property PACKAGE_PIN D11 [get_ports "FMC1_PRSNT_B"]
set_property IOSTANDARD LVCMOS33 [get_ports "FMC1_PRSNT_B"]
# Drive high to enable output CLK_BIDIR2 and CLK_BIDIR3 as C2M
set_property PACKAGE_PIN D10 [get_ports "FMC1_CLK_DIR"]
set_property IOSTANDARD LVCMOS33 [get_ports "FMC1_CLK_DIR"]

# FMC CLK_M2C0 and CLK_BIDIR2 to clk mux; CLK_M2C1 and CLK_BIDIR3 to FPGA
set_property PACKAGE_PIN AM34 [get_ports "FMC1_CLK_M2C_N1"]
set_property PACKAGE_PIN AL34 [get_ports "FMC1_CLK_M2C_P1"]
set_property PACKAGE_PIN AM33 [get_ports "FMC1_CLK_M2C_N3"]
set_property PACKAGE_PIN AM32 [get_ports "FMC1_CLK_M2C_P3"]
set_property PACKAGE_PIN AN28 [get_ports "FMC1_CLK_C2M_N3"]
set_property PACKAGE_PIN AM28 [get_ports "FMC1_CLK_C2M_P3"]
# HP bank
set_property PACKAGE_PIN AK34 [get_ports "FMC1_LA_N0"]
set_property PACKAGE_PIN AK33 [get_ports "FMC1_LA_P0"]
set_property PACKAGE_PIN AN36 [get_ports "FMC1_LA_N1"]
set_property PACKAGE_PIN AN35 [get_ports "FMC1_LA_P1"]
set_property PACKAGE_PIN AK39 [get_ports "FMC1_LA_N2"]
set_property PACKAGE_PIN AJ39 [get_ports "FMC1_LA_P2"]
set_property PACKAGE_PIN AK38 [get_ports "FMC1_LA_N3"]
set_property PACKAGE_PIN AK37 [get_ports "FMC1_LA_P3"]
set_property PACKAGE_PIN AK35 [get_ports "FMC1_LA_N4"]
set_property PACKAGE_PIN AJ34 [get_ports "FMC1_LA_P4"]
set_property PACKAGE_PIN AN37 [get_ports "FMC1_LA_N5"]
set_property PACKAGE_PIN AM37 [get_ports "FMC1_LA_P5"]
set_property PACKAGE_PIN AN38 [get_ports "FMC1_LA_N6"]
set_property PACKAGE_PIN AM38 [get_ports "FMC1_LA_P6"]
set_property PACKAGE_PIN AH32 [get_ports "FMC1_LA_N7"]
set_property PACKAGE_PIN AH31 [get_ports "FMC1_LA_P7"]
set_property PACKAGE_PIN AJ33 [get_ports "FMC1_LA_N8"]
set_property PACKAGE_PIN AH33 [get_ports "FMC1_LA_P8"]
set_property PACKAGE_PIN AL37 [get_ports "FMC1_LA_N9"]
set_property PACKAGE_PIN AL36 [get_ports "FMC1_LA_P9"]
set_property PACKAGE_PIN AM35 [get_ports "FMC1_LA_N10"]
set_property PACKAGE_PIN AL35 [get_ports "FMC1_LA_P10"]
set_property PACKAGE_PIN AJ30 [get_ports "FMC1_LA_N11"]
set_property PACKAGE_PIN AJ29 [get_ports "FMC1_LA_P11"]
set_property PACKAGE_PIN AJ31 [get_ports "FMC1_LA_N12"]
set_property PACKAGE_PIN AH30 [get_ports "FMC1_LA_P12"]
set_property PACKAGE_PIN AL31 [get_ports "FMC1_LA_N13"]
set_property PACKAGE_PIN AK31 [get_ports "FMC1_LA_P13"]
set_property PACKAGE_PIN AN33 [get_ports "FMC1_LA_N14"]
set_property PACKAGE_PIN AN32 [get_ports "FMC1_LA_P14"]
set_property PACKAGE_PIN AM29 [get_ports "FMC1_LA_N15"]
set_property PACKAGE_PIN AL29 [get_ports "FMC1_LA_P15"]
set_property PACKAGE_PIN AN31 [get_ports "FMC1_LA_N16"]
set_property PACKAGE_PIN AN30 [get_ports "FMC1_LA_P16"]
# 1.0V: POD10 and DIFF_POD10
# 1.2V: LVCMOS12 and DIFF_HSUL_12
# 1.5V: LVCMOS15 and DIFF_SSTL15
# 1.8V: LVCMOS18 and LVDS
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N0"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P0"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N1"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P1"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N2"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P2"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N3"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P3"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N4"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P4"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N5"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P5"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N6"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P6"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N7"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P7"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N8"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P8"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N9"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P9"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N10"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P10"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N11"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P11"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N12"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P12"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N13"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P13"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N14"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P14"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N15"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P15"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_N16"]
set_property IOSTANDARD LVCMOS18  [get_ports "FMC1_LA_P16"]

# HB for monitoring
set_property PACKAGE_PIN E8  [get_ports "FMC1_HB_N0"]
set_property PACKAGE_PIN F9  [get_ports "FMC1_HB_P0"]
set_property PACKAGE_PIN A9  [get_ports "FMC1_HB_N1"]
set_property PACKAGE_PIN B10 [get_ports "FMC1_HB_P1"]
set_property PACKAGE_PIN E9  [get_ports "FMC1_HB_N2"]
set_property PACKAGE_PIN E10 [get_ports "FMC1_HB_P2"]
set_property PACKAGE_PIN A11 [get_ports "FMC1_HB_N3"]
set_property PACKAGE_PIN B11 [get_ports "FMC1_HB_P3"]
set_property PACKAGE_PIN A7  [get_ports "FMC1_HB_N4"]
set_property PACKAGE_PIN B7  [get_ports "FMC1_HB_P4"]
set_property PACKAGE_PIN A8  [get_ports "FMC1_HB_N5"]
set_property PACKAGE_PIN B9  [get_ports "FMC1_HB_P5"]
set_property PACKAGE_PIN E6  [get_ports "FMC1_HB_N6"]
set_property PACKAGE_PIN F6  [get_ports "FMC1_HB_P6"]
set_property PACKAGE_PIN F7  [get_ports "FMC1_HB_N7"]
set_property PACKAGE_PIN F8  [get_ports "FMC1_HB_P7"]
set_property IOSTANDARD  LVCMOS33 [get_ports "FMC1_HB_P*"]
set_property IOSTANDARD  LVCMOS33 [get_ports "FMC1_HB_N*"]

# GTY for FMC1
# BANK_130
# set_property PACKAGE_PIN T36 [get_ports "FMC1_DP_M2C_P3"]
# set_property PACKAGE_PIN T37 [get_ports "FMC1_DP_M2C_N3"]
# set_property PACKAGE_PIN R38 [get_ports "FMC1_DP_M2C_P2"]
# set_property PACKAGE_PIN R39 [get_ports "FMC1_DP_M2C_N2"]
# set_property PACKAGE_PIN P36 [get_ports "FMC1_DP_M2C_P1"]
# set_property PACKAGE_PIN P37 [get_ports "FMC1_DP_M2C_N1"]
# set_property PACKAGE_PIN N38 [get_ports "FMC1_DP_M2C_P0"]
# set_property PACKAGE_PIN N39 [get_ports "FMC1_DP_M2C_N0"]
# set_property PACKAGE_PIN P31 [get_ports "FMC1_DP_C2M_P3"]
# set_property PACKAGE_PIN P32 [get_ports "FMC1_DP_C2M_N3"]
# set_property PACKAGE_PIN N33 [get_ports "FMC1_DP_C2M_P2"]
# set_property PACKAGE_PIN N34 [get_ports "FMC1_DP_C2M_N2"]
# set_property PACKAGE_PIN M31 [get_ports "FMC1_DP_C2M_P1"]
# set_property PACKAGE_PIN M32 [get_ports "FMC1_DP_C2M_N1"]
# set_property PACKAGE_PIN L33 [get_ports "FMC1_DP_C2M_P0"]
# set_property PACKAGE_PIN L34 [get_ports "FMC1_DP_C2M_N0"]
# set_property PACKAGE_PIN V27 [get_ports "MGTCLK130_P0"]
# set_property PACKAGE_PIN V28 [get_ports "MGTCLK130_N0"]
# set_property PACKAGE_PIN U29 [get_ports "MGTCLK130_P1"]
# set_property PACKAGE_PIN U30 [get_ports "MGTCLK130_N1"]

# BANK_129
# set_property PACKAGE_PIN Y36 [get_ports "FMC1_DP_M2C_P7"]
# set_property PACKAGE_PIN Y37 [get_ports "FMC1_DP_M2C_N7"]
# set_property PACKAGE_PIN W38 [get_ports "FMC1_DP_M2C_P6"]
# set_property PACKAGE_PIN W39 [get_ports "FMC1_DP_M2C_N6"]
# set_property PACKAGE_PIN V36 [get_ports "FMC1_DP_M2C_P5"]
# set_property PACKAGE_PIN V37 [get_ports "FMC1_DP_M2C_N5"]
# set_property PACKAGE_PIN U38 [get_ports "FMC1_DP_M2C_P4"]
# set_property PACKAGE_PIN U39 [get_ports "FMC1_DP_M2C_N4"]
# set_property PACKAGE_PIN V31 [get_ports "FMC1_DP_C2M_P7"]
# set_property PACKAGE_PIN V32 [get_ports "FMC1_DP_C2M_N7"]
# set_property PACKAGE_PIN U33 [get_ports "FMC1_DP_C2M_P6"]
# set_property PACKAGE_PIN U34 [get_ports "FMC1_DP_C2M_N6"]
# set_property PACKAGE_PIN T31 [get_ports "FMC1_DP_C2M_P5"]
# set_property PACKAGE_PIN T32 [get_ports "FMC1_DP_C2M_N5"]
# set_property PACKAGE_PIN R33 [get_ports "FMC1_DP_C2M_P4"]
# set_property PACKAGE_PIN R34 [get_ports "FMC1_DP_C2M_N4"]
# set_property PACKAGE_PIN Y27 [get_ports "MGTCLK129_P0"]
# set_property PACKAGE_PIN Y28 [get_ports "MGTCLK129_N0"]
# set_property PACKAGE_PIN W29 [get_ports "MGTCLK129_P1"]
# set_property PACKAGE_PIN W30 [get_ports "MGTCLK129_N1"]

##############################################################################
# FIREFLY
set_property PACKAGE_PIN C4 [get_ports "FIREFLY_MODSEL"]
set_property PACKAGE_PIN C5 [get_ports "FIREFLY_MODPRSL"]
set_property PACKAGE_PIN C3 [get_ports "FIREFLY_INTL"]
set_property PACKAGE_PIN D3 [get_ports "FIREFLY_RESETL"]
set_property IOSTANDARD LVCMOS33 [get_ports "FIREFLY_MODSEL"]
set_property IOSTANDARD LVCMOS33 [get_ports "FIREFLY_MODPRSL"]
set_property IOSTANDARD LVCMOS33 [get_ports "FIREFLY_INTL"]
set_property IOSTANDARD LVCMOS33 [get_ports "FIREFLY_RESETL"]

# BANK_132
# set_property PACKAGE_PIN H36 [get_ports "FIREFLY_M2C_P0"]
# set_property PACKAGE_PIN H37 [get_ports "FIREFLY_M2C_N0"]
# set_property PACKAGE_PIN G38 [get_ports "FIREFLY_M2C_P1"]
# set_property PACKAGE_PIN G39 [get_ports "FIREFLY_M2C_N1"]
# set_property PACKAGE_PIN E38 [get_ports "FIREFLY_M2C_P2"]
# set_property PACKAGE_PIN E39 [get_ports "FIREFLY_M2C_N2"]
# set_property PACKAGE_PIN C38 [get_ports "FIREFLY_M2C_P3"]
# set_property PACKAGE_PIN C39 [get_ports "FIREFLY_M2C_N3"]
# set_property PACKAGE_PIN D35 [get_ports "FIREFLY_C2M_P0"]
# set_property PACKAGE_PIN D36 [get_ports "FIREFLY_C2M_N0"]
# set_property PACKAGE_PIN C33 [get_ports "FIREFLY_C2M_P1"]
# set_property PACKAGE_PIN C34 [get_ports "FIREFLY_C2M_N1"]
# set_property PACKAGE_PIN B35 [get_ports "FIREFLY_C2M_P2"]
# set_property PACKAGE_PIN B36 [get_ports "FIREFLY_C2M_N2"]
# set_property PACKAGE_PIN A33 [get_ports "FIREFLY_C2M_P3"]
# set_property PACKAGE_PIN A34 [get_ports "FIREFLY_C2M_N3"]
# set_property PACKAGE_PIN P27 [get_ports "MGTCLK132_P0"]
# set_property PACKAGE_PIN P28 [get_ports "MGTCLK132_N0"]

##############################################################################
# AMC
set_property PACKAGE_PIN J10 [get_ports "AMC_MODE"]
set_property IOSTANDARD LVCMOS25  [get_ports "AMC_MODE"]

# Port0~3 bank_231
# set_property PACKAGE_PIN L4 [get_ports "AMC_RX_P3"]
# set_property PACKAGE_PIN L3 [get_ports "AMC_RX_N3"]
# set_property PACKAGE_PIN K2 [get_ports "AMC_RX_P2"]
# set_property PACKAGE_PIN K1 [get_ports "AMC_RX_N2"]
# set_property PACKAGE_PIN J4 [get_ports "AMC_RX_P1"]
# set_property PACKAGE_PIN J3 [get_ports "AMC_RX_N1"]
# set_property PACKAGE_PIN H2 [get_ports "AMC_RX_P0"]
# set_property PACKAGE_PIN H1 [get_ports "AMC_RX_N0"]
# set_property PACKAGE_PIN L8 [get_ports "AMC_TX_P3"]
# set_property PACKAGE_PIN L7 [get_ports "AMC_TX_N3"]
# set_property PACKAGE_PIN K6 [get_ports "AMC_TX_P2"]
# set_property PACKAGE_PIN K5 [get_ports "AMC_TX_N2"]
# set_property PACKAGE_PIN J8 [get_ports "AMC_TX_P1"]
# set_property PACKAGE_PIN J7 [get_ports "AMC_TX_N1"]
# set_property PACKAGE_PIN H6 [get_ports "AMC_TX_P0"]
# set_property PACKAGE_PIN H5 [get_ports "AMC_TX_N0"]
# set_property PACKAGE_PIN U12 [get_ports "MGTCLK231_P0"]
# set_property PACKAGE_PIN U11 [get_ports "MGTCLK231_N0"]
# set_property PACKAGE_PIN T10 [get_ports "MGTCLK231_P1"]
# set_property PACKAGE_PIN T9  [get_ports "MGTCLK231_N1"]

# Port4~7 bank_229
# set_property PACKAGE_PIN W4 [get_ports "AMC_RX_P7"]
# set_property PACKAGE_PIN W3 [get_ports "AMC_RX_N7"]
# set_property PACKAGE_PIN V2 [get_ports "AMC_RX_P6"]
# set_property PACKAGE_PIN V1 [get_ports "AMC_RX_N6"]
# set_property PACKAGE_PIN U4 [get_ports "AMC_RX_P5"]
# set_property PACKAGE_PIN U3 [get_ports "AMC_RX_N5"]
# set_property PACKAGE_PIN T2 [get_ports "AMC_RX_P4"]
# set_property PACKAGE_PIN T1 [get_ports "AMC_RX_N4"]
# set_property PACKAGE_PIN W8 [get_ports "AMC_TX_P7"]
# set_property PACKAGE_PIN W7 [get_ports "AMC_TX_N7"]
# set_property PACKAGE_PIN V6 [get_ports "AMC_TX_P6"]
# set_property PACKAGE_PIN V5 [get_ports "AMC_TX_N6"]
# set_property PACKAGE_PIN U8 [get_ports "AMC_TX_P5"]
# set_property PACKAGE_PIN U7 [get_ports "AMC_TX_N5"]
# set_property PACKAGE_PIN T6 [get_ports "AMC_TX_P4"]
# set_property PACKAGE_PIN T5 [get_ports "AMC_TX_N4"]
# set_property PACKAGE_PIN AA12 [get_ports "MGTCLK229_P0"]
# set_property PACKAGE_PIN AA11 [get_ports "MGTCLK229_N0"]

# Port8~11 bank_228
# set_property PACKAGE_PIN AC4 [get_ports "AMC_RX_P11"]
# set_property PACKAGE_PIN AC3 [get_ports "AMC_RX_N11"]
# set_property PACKAGE_PIN AB2 [get_ports "AMC_RX_P10"]
# set_property PACKAGE_PIN AB1 [get_ports "AMC_RX_N10"]
# set_property PACKAGE_PIN AA4 [get_ports "AMC_RX_P9"]
# set_property PACKAGE_PIN AA3 [get_ports "AMC_RX_N9"]
# set_property PACKAGE_PIN Y2  [get_ports "AMC_RX_P8"]
# set_property PACKAGE_PIN Y1  [get_ports "AMC_RX_N8"]
# set_property PACKAGE_PIN AC8 [get_ports "AMC_TX_P11"]
# set_property PACKAGE_PIN AC7 [get_ports "AMC_TX_N11"]
# set_property PACKAGE_PIN AB6 [get_ports "AMC_TX_P10"]
# set_property PACKAGE_PIN AB5 [get_ports "AMC_TX_N10"]
# set_property PACKAGE_PIN AA8 [get_ports "AMC_TX_P9"]
# set_property PACKAGE_PIN AA7 [get_ports "AMC_TX_N9"]
# set_property PACKAGE_PIN Y6  [get_ports "AMC_TX_P8"]
# set_property PACKAGE_PIN Y5  [get_ports "AMC_TX_N8"]
# set_property PACKAGE_PIN AC12 [get_ports "MGTCLK228_P0"]
# set_property PACKAGE_PIN AC11 [get_ports "MGTCLK228_N0"]

# Port12~15 bank_230
# set_property PACKAGE_PIN R4 [get_ports "AMC_RX_P15"]
# set_property PACKAGE_PIN R3 [get_ports "AMC_RX_N15"]
# set_property PACKAGE_PIN P2 [get_ports "AMC_RX_P14"]
# set_property PACKAGE_PIN P1 [get_ports "AMC_RX_N14"]
# set_property PACKAGE_PIN N4 [get_ports "AMC_RX_P13"]
# set_property PACKAGE_PIN N3 [get_ports "AMC_RX_N13"]
# set_property PACKAGE_PIN M2 [get_ports "AMC_RX_P12"]
# set_property PACKAGE_PIN M1 [get_ports "AMC_RX_N12"]
# set_property PACKAGE_PIN R8 [get_ports "AMC_TX_P15"]
# set_property PACKAGE_PIN R7 [get_ports "AMC_TX_N15"]
# set_property PACKAGE_PIN P6 [get_ports "AMC_TX_P14"]
# set_property PACKAGE_PIN P5 [get_ports "AMC_TX_N14"]
# set_property PACKAGE_PIN N8 [get_ports "AMC_TX_P13"]
# set_property PACKAGE_PIN N7 [get_ports "AMC_TX_N13"]
# set_property PACKAGE_PIN M6 [get_ports "AMC_TX_P12"]
# set_property PACKAGE_PIN M5 [get_ports "AMC_TX_N12"]
# set_property PACKAGE_PIN W12 [get_ports "MGTCLK230_P0"]
# set_property PACKAGE_PIN W11 [get_ports "MGTCLK230_N0"]

# Port17~20 LVDS
set_property PACKAGE_PIN N12 [get_ports "AMC_TX17"]
set_property PACKAGE_PIN M11 [get_ports "AMC_TX18"]
set_property PACKAGE_PIN N13 [get_ports "AMC_TX19"]
set_property PACKAGE_PIN N15 [get_ports "AMC_TX20"]
# Drive high to output, low to input
set_property PACKAGE_PIN K13 [get_ports "AMC_TX_DE17"]
set_property PACKAGE_PIN N10 [get_ports "AMC_TX_DE18"]
set_property PACKAGE_PIN P11 [get_ports "AMC_TX_DE19"]
set_property PACKAGE_PIN R15 [get_ports "AMC_TX_DE20"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_TX17"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_TX18"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_TX19"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_TX20"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_TX_DE17"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_TX_DE18"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_TX_DE19"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_TX_DE20"]

set_property PACKAGE_PIN L14 [get_ports "AMC_RX17"]
set_property PACKAGE_PIN M12 [get_ports "AMC_RX18"]
set_property PACKAGE_PIN M14 [get_ports "AMC_RX19"]
set_property PACKAGE_PIN N14 [get_ports "AMC_RX20"]
# Drive high to output, low to input
set_property PACKAGE_PIN P13 [get_ports "AMC_RX_DE17"]
set_property PACKAGE_PIN M10 [get_ports "AMC_RX_DE18"]
set_property PACKAGE_PIN P10 [get_ports "AMC_RX_DE19"]
set_property PACKAGE_PIN P15 [get_ports "AMC_RX_DE20"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_RX17"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_RX18"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_RX19"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_RX20"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_RX_DE17"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_RX_DE18"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_RX_DE19"]
set_property IOSTANDARD LVCMOS33 [get_ports "AMC_RX_DE20"]

##############################################################################
# RTM
set_property PACKAGE_PIN K11 [get_ports "RTM_PS_B"]
set_property PACKAGE_PIN L11 [get_ports "RTM_IO3"]
set_property PACKAGE_PIN L12 [get_ports "RTM_IO2"]
set_property PACKAGE_PIN L13 [get_ports "RTM_IO1"]
set_property PACKAGE_PIN R14 [get_ports "RTM_IO0"]
set_property IOSTANDARD LVCMOS33 [get_ports "RTM_PS_B"]
set_property IOSTANDARD LVCMOS33 [get_ports "RTM_IO*"]

# bank_227
# set_property PACKAGE_PIN AG4 [get_ports "RTM2AMC_P3"]
# set_property PACKAGE_PIN AG3 [get_ports "RTM2AMC_N3"]
# set_property PACKAGE_PIN AF2 [get_ports "RTM2AMC_P2"]
# set_property PACKAGE_PIN AF1 [get_ports "RTM2AMC_N2"]
# set_property PACKAGE_PIN AE4 [get_ports "RTM2AMC_P1"]
# set_property PACKAGE_PIN AE3 [get_ports "RTM2AMC_N1"]
# set_property PACKAGE_PIN AD2 [get_ports "RTM2AMC_P0"]
# set_property PACKAGE_PIN AD1 [get_ports "RTM2AMC_N0"]
# set_property PACKAGE_PIN AG8 [get_ports "AMC2RTM_P3"]
# set_property PACKAGE_PIN AG7 [get_ports "AMC2RTM_N3"]
# set_property PACKAGE_PIN AF6 [get_ports "AMC2RTM_P2"]
# set_property PACKAGE_PIN AF5 [get_ports "AMC2RTM_N2"]
# set_property PACKAGE_PIN AE8 [get_ports "AMC2RTM_P1"]
# set_property PACKAGE_PIN AE7 [get_ports "AMC2RTM_N1"]
# set_property PACKAGE_PIN AD6 [get_ports "AMC2RTM_P0"]
# set_property PACKAGE_PIN AD5 [get_ports "AMC2RTM_N0"]
# set_property PACKAGE_PIN AE12 [get_ports "MGTCLK227_P0"]
# set_property PACKAGE_PIN AE11 [get_ports "MGTCLK227_N0"]
# set_property PACKAGE_PIN AD10 [get_ports "MGTCLK227_P1"]
# set_property PACKAGE_PIN AD9  [get_ports "MGTCLK227_N1"]

# bank_226
# set_property PACKAGE_PIN AL4 [get_ports "RTM2AMC_P7"]
# set_property PACKAGE_PIN AL3 [get_ports "RTM2AMC_N7"]
# set_property PACKAGE_PIN AK2 [get_ports "RTM2AMC_P6"]
# set_property PACKAGE_PIN AK1 [get_ports "RTM2AMC_N6"]
# set_property PACKAGE_PIN AJ4 [get_ports "RTM2AMC_P5"]
# set_property PACKAGE_PIN AJ3 [get_ports "RTM2AMC_N5"]
# set_property PACKAGE_PIN AH2 [get_ports "RTM2AMC_P4"]
# set_property PACKAGE_PIN AH1 [get_ports "RTM2AMC_N4"]
# set_property PACKAGE_PIN AL8 [get_ports "AMC2RTM_P7"]
# set_property PACKAGE_PIN AL7 [get_ports "AMC2RTM_N7"]
# set_property PACKAGE_PIN AK6 [get_ports "AMC2RTM_P6"]
# set_property PACKAGE_PIN AK5 [get_ports "AMC2RTM_N6"]
# set_property PACKAGE_PIN AJ8 [get_ports "AMC2RTM_P5"]
# set_property PACKAGE_PIN AJ7 [get_ports "AMC2RTM_N5"]
# set_property PACKAGE_PIN AH6 [get_ports "AMC2RTM_P4"]
# set_property PACKAGE_PIN AH5 [get_ports "AMC2RTM_N4"]
# set_property PACKAGE_PIN AG12 [get_ports "MGTCLK226_P0"]
# set_property PACKAGE_PIN AG11 [get_ports "MGTCLK226_N0"]
# set_property PACKAGE_PIN AF10 [get_ports "MGTCLK226_P1"]
# set_property PACKAGE_PIN AF9  [get_ports "MGTCLK226_N1"]

# bank_225
# set_property PACKAGE_PIN AR4 [get_ports "RTM2AMC_P11"]
# set_property PACKAGE_PIN AR3 [get_ports "RTM2AMC_N11"]
# set_property PACKAGE_PIN AP2 [get_ports "RTM2AMC_P10"]
# set_property PACKAGE_PIN AP1 [get_ports "RTM2AMC_N10"]
# set_property PACKAGE_PIN AN4 [get_ports "RTM2AMC_P9"]
# set_property PACKAGE_PIN AN3 [get_ports "RTM2AMC_N9"]
# set_property PACKAGE_PIN AM2 [get_ports "RTM2AMC_P8"]
# set_property PACKAGE_PIN AM1 [get_ports "RTM2AMC_N8"]
# set_property PACKAGE_PIN AR8 [get_ports "AMC2RTM_P11"]
# set_property PACKAGE_PIN AR7 [get_ports "AMC2RTM_N11"]
# set_property PACKAGE_PIN AP6 [get_ports "AMC2RTM_P10"]
# set_property PACKAGE_PIN AP5 [get_ports "AMC2RTM_N10"]
# set_property PACKAGE_PIN AN8 [get_ports "AMC2RTM_P9"]
# set_property PACKAGE_PIN AN7 [get_ports "AMC2RTM_N9"]
# set_property PACKAGE_PIN AM6 [get_ports "AMC2RTM_P8"]
# set_property PACKAGE_PIN AM5 [get_ports "AMC2RTM_N8"]
# set_property PACKAGE_PIN AJ12 [get_ports "MGTCLK225_P0"]
# set_property PACKAGE_PIN AJ11 [get_ports "MGTCLK225_N0"]
# set_property PACKAGE_PIN AH10 [get_ports "MGTCLK225_P1"]
# set_property PACKAGE_PIN AH9  [get_ports "MGTCLK225_N1"]

# bank_224
# set_property PACKAGE_PIN AW4  [get_ports "RTM2AMC_P15"]
# set_property PACKAGE_PIN AW3  [get_ports "RTM2AMC_N15"]
# set_property PACKAGE_PIN AV2  [get_ports "RTM2AMC_P14"]
# set_property PACKAGE_PIN AV1  [get_ports "RTM2AMC_N14"]
# set_property PACKAGE_PIN AU4  [get_ports "RTM2AMC_P13"]
# set_property PACKAGE_PIN AU3  [get_ports "RTM2AMC_N13"]
# set_property PACKAGE_PIN AT2  [get_ports "RTM2AMC_P12"]
# set_property PACKAGE_PIN AT1  [get_ports "RTM2AMC_N12"]
# set_property PACKAGE_PIN AW8  [get_ports "AMC2RTM_P15"]
# set_property PACKAGE_PIN AW7  [get_ports "AMC2RTM_N15"]
# set_property PACKAGE_PIN AV6  [get_ports "AMC2RTM_P14"]
# set_property PACKAGE_PIN AV5  [get_ports "AMC2RTM_N14"]
# set_property PACKAGE_PIN AU8  [get_ports "AMC2RTM_P13"]
# set_property PACKAGE_PIN AU7  [get_ports "AMC2RTM_N13"]
# set_property PACKAGE_PIN AT6  [get_ports "AMC2RTM_P12"]
# set_property PACKAGE_PIN AT5  [get_ports "AMC2RTM_N12"]
# set_property PACKAGE_PIN AM10 [get_ports "MGTCLK224_P0"]
# set_property PACKAGE_PIN AM9  [get_ports "MGTCLK224_N0"]
# set_property PACKAGE_PIN AK10 [get_ports "MGTCLK224_P1"]
# set_property PACKAGE_PIN AK9  [get_ports "MGTCLK224_N1"]

# bank_131
# set_property PACKAGE_PIN M36 [get_ports "RTM2AMC_P16"]
# set_property PACKAGE_PIN M37 [get_ports "RTM2AMC_N16"]
# set_property PACKAGE_PIN L38 [get_ports "RTM2AMC_P17"]
# set_property PACKAGE_PIN L39 [get_ports "RTM2AMC_N17"]
# set_property PACKAGE_PIN K36 [get_ports "RTM2AMC_P18"]
# set_property PACKAGE_PIN K37 [get_ports "RTM2AMC_N18"]
# set_property PACKAGE_PIN J38 [get_ports "RTM2AMC_P19"]
# set_property PACKAGE_PIN J39 [get_ports "RTM2AMC_N19"]
# set_property PACKAGE_PIN J33 [get_ports "AMC2RTM_P16"]
# set_property PACKAGE_PIN J34 [get_ports "AMC2RTM_N16"]
# set_property PACKAGE_PIN G33 [get_ports "AMC2RTM_P17"]
# set_property PACKAGE_PIN G34 [get_ports "AMC2RTM_N17"]
# set_property PACKAGE_PIN F35 [get_ports "AMC2RTM_P18"]
# set_property PACKAGE_PIN F36 [get_ports "AMC2RTM_N18"]
# set_property PACKAGE_PIN E33 [get_ports "AMC2RTM_P19"]
# set_property PACKAGE_PIN E34 [get_ports "AMC2RTM_N19"]
# set_property PACKAGE_PIN T27 [get_ports "MGTCLK131_P0"]
# set_property PACKAGE_PIN T28 [get_ports "MGTCLK131_N0"]
